### ISSUE TITLE
Lost all entities and devices

### ISSUE THREAD

**Issue by jacknorris123** [maciej-or/hikvision_next#104]
Hi all, funny one, lost all entities and devices and just left with 4 entities for the nor around ports, url etc.

Any ideas?

Network Video Recorder Alarm Server IP
sensor.ds_7604ni_k1_4p_b_0420191212ccrre00260806wcvu_alarm_server_ipaddress
Hikvision NVR / IP Camera
Hall
—
—

 
Network Video Recorder Alarm Server Path
sensor.ds_7604ni_k1_4p_b_0420191212ccrre00260806wcvu_alarm_server_url
Hikvision NVR / IP Camera
Hall
—
—

 
Network Video Recorder Alarm Server Port
sensor.ds_7604ni_k1_4p_b_0420191212ccrre00260806wcvu_alarm_server_portno
Hikvision NVR / IP Camera
Hall
—
—

 
Network Video Recorder Alarm Server Protocol
sensor.ds_7604ni_k1_4p_b_0420191212ccrre00260806wcvu_alarm_server_protocoltype
Hikvision NVR / IP Camera
Hall
—
—

 
Network Video Recorder Holiday mode
switch.ds_7604ni_k1_4p_b_0420191212ccrre00260806wcvu_holiday_mode
Hikvision NVR / IP Camera
Hall
—

**Comment by maciej-or** [comment]
please share more details, did it occur after integration upgrade?
