### ISSUE TITLE
Once I add this integration, "Add Integration" button stops working

### ISSUE THREAD

**Issue by ondrupls** [maciej-or/hikvision_next#106]
Hello,

first of all, thank you for looking into my issue. Your integration is just what Ive been looking for for a while now, at least I think so, because I actually did not manage to set it up yet.

The title pretty much says it all - once I add your integration using HACS, my "Add Integration" button in Devices and Services doesnt work, I can click on it, but the options are being loaded (theres the leading circle animation and nothing ever happens).. Once I remove the integration, it suddenly works again. I am a selfteaching newbie in HA but Ive managed a lot in it so far, so when you tell me how to find information you need to diagnose the problem, I should be able to get it for you.

Thank you very much.

Ondrej

**Comment by maciej-or** [comment]
Try reload page keeping shift button pressed.

**Comment by ondrupls** [comment]
> Try reload page keeping shift button pressed.

Didnt help :(

**Comment by maciej-or** [comment]
You could restart HA (to clear old logs) and repeat adding integration. Then check Settings -> System -> Logs if there is something related to this integration.

**Comment by ondrupls** [comment]
> You could restart HA (to clear old logs) and repeat adding integration. Then check Settings -> System -> Logs if there is something related to this integration.

Restarting, removing and readding the integration was the first thing I did.. hasnt worked :/  may I suggest an MS Teams session maybe? Nothing in the logs btw :/

**Comment by maciej-or** [comment]
If there are no log entries related to this integration I'd suggest asking HA community.

**Comment by ondrupls** [comment]
> If there are no log entries related to this integration I'd suggest asking HA community.

Well, thats a bit dissapointing,since its very much obvious that its the integration what is causing the issue,because as soon as I remove it,everything works perfectly. But okay, thanks, I guess…
