### ISSUE TITLE
live view bug

### ISSUE THREAD

**Issue by basselamr15** [maciej-or/hikvision_next#111]
whenever i try to get live view from my nvr and camera it just show as a picture that gets updated every 10 second and no live view so can someone help me get live view on my home assistant dashboard?
![image](https://github.com/maciej-or/hikvision_next/assets/141641936/095ca7ad-66b1-49f6-8f8d-0a47421f39ed)
whenever i try to get live view from my nvr and camera it just show as a picture that gets updated every 10 second and no live view

**Comment by maciej-or** [comment]
for single camera click EDIT and select `live` option 
![image](https://github.com/maciej-or/hikvision_next/assets/38075949/8a5bff33-57ee-4c4f-9c52-b343b12c127e)

for more cameras I'd suggest installing `RTSPtoWeb - WebRTC` Add-on and using its multiview

**Comment by basselamr15** [comment]
I already did that and still the same

**Comment by maciej-or** [comment]
What is CPU usage? You could track sensor.processor_use_percent entity. Your HA host might have not enough resources.

**Comment by basselamr15** [comment]
im sorry but can you explain this in a simple way?

**Comment by basselamr15** [comment]
my system consists of hikvision nvr and camera which im trying to integrate with fibaro home center 3 to create a smart home so to do that i had to use home assistant to connect both devices together, so when u say not enough resources do you mean on my home center or my actual laptop?

**Comment by FirewizzNL** [comment]
I had the same, there is a bug that does not correctly encodes the url. So if the password contains special characters the url gets broken. You can work around this by making a password with - as special characters(that does not need encoding).

**Comment by maciej-or** [comment]
good catch, thank you
definitely I need to write unit tests to cover cases like that

**Comment by mbarnes106** [comment]
I have the same problem. I get a snapshot that updates every 10 seconds but no live view.
If I make my own picture elements card with below code it does not update in lovelace at all unless i click on it to load full preview, and even then it just gives another snapshot

`show_state: true
show_name: true
camera_view: live
type: picture-entity
entity: camera.ds_7604ni_k1_4p0420211019ccrrg19140069wcvu_101
camera_image: camera.ds_7604ni_k1_4p0420211019ccrrg19140069wcvu_101
`

![Capture](https://github.com/maciej-or/hikvision_next/assets/51041880/32a5e753-98fd-4181-96d2-0961e74caec1)
