### ISSUE TITLE
Feature Request: Reboot NVR

### ISSUE THREAD

**Issue by stamandr** [maciej-or/hikvision_next#115]
Is it possible to add a reboot feature to reboot NVR and cameras ?

**Comment by maciej-or** [comment]
yes, it should be relatively easy, simple PUT /ISAPI/System/reboot, it would be available as Home Assistant service

**Comment by stamandr** [comment]
Thanks.... Can you please elaborate. I can't find any Home Assistant service in regards to this.

**Comment by maciej-or** [comment]
It needs an implementation, I wrote what's the plan :)

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.19
