### ISSUE TITLE
PIR alarm DS-2CD2420F-I

### ISSUE THREAD

**Issue by TokarevSergey** [maciej-or/hikvision_next#122]
Good evening.  Tell me if it is possible to deliver a PIR alarm switch.
Thank you.
Camera DS
![Screenshot_20231003_223559_Chrome](https://github.com/maciej-or/hikvision_next/assets/98225056/888d9f2f-0a33-442c-a447-7ddbcce1d01c)
-2CD2420F-I.

**Comment by maciej-or** [comment]
Duplicate of #1 

@TokarevSergey for the future please change language to English before taking screenshots.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.17
