### ISSUE TITLE
line crossing / intrusion detection issue

### ISSUE THREAD

**Issue by przemekp833** [maciej-or/hikvision_next#129]
Hi, 

First of all, thanks for the great integration. 

I do have an issue with the intrusion detection motion entities. It remains clear all times. I want to use them for other automations. 
I have the hik connect app, detection works fine there. Perhaps, there is an issue with setting it up, but it all seems ok. 
I would appreciate any directions. Thx

![image](https://github.com/maciej-or/hikvision_next/assets/152802870/703922f6-3968-4543-b51a-f468701b2cf5)

**Comment by maciej-or** [comment]
Do you receive other notifications? All of them should appear in the Logbook section. If it's related to intrusion detection only I'd need a log when event is triggered. See here how to catch that https://github.com/maciej-or/hikvision_next#reporting-issues
If you don't get notifications, it's most likely wrong settings for Alarm Server, please read explanation here https://github.com/maciej-or/hikvision_next/issues/23

**Comment by przemekp833** [comment]
Cheers! It seems like the Alarm Server is set up wrong. I will try to fix it
