### ISSUE TITLE
Feature request: stream

### ISSUE THREAD

**Issue by Tanjohnson99** [maciej-or/hikvision_next#13]
Hi, could be good to integrate the stream of the cameras. 

Thanks

**Comment by maciej-or** [comment]
Streams is the feature I definitely would like to add.  As far I use `RTSPtoWeb - WebRTC` add on. It has lower latency than simple RTSP streams I tried to add. So I need spend a bit more time to figure out this topic.

**Comment by Tanjohnson99** [comment]
Ok. Thanks. I would like to help but i don't undersant very well code. 

Best

**Comment by maciej-or** [comment]
stream feature has been released https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.4
