### ISSUE TITLE
Missing Alarm server tab

### ISSUE THREAD

**Issue by hpeterka** [maciej-or/hikvision_next#134]
Hello.
Firstly, I want to thank author for great integration.

I have NVR DS-7616NXI-K2 with firmware V4.75.005 build 230630. There is no tab "Alarm server". I have only "Other" tab.
![Screenshot from 2023-12-28 16-18-31](https://github.com/maciej-or/hikvision_next/assets/3702814/5ba36953-c651-4e6d-aa2b-046002d6cd8b)

When I completed initial setup (with checked Set alarm server), I was able to see all my cameras in HA, but binary sensor was not working.

Does anyone have similar experience?

Thanks!

**Comment by vytautasgimbutas** [comment]
Hi, same here.

**Comment by romzzz13** [comment]
Hi, same here.
