### ISSUE TITLE
Video preview not working

### ISSUE THREAD

**Issue by Metam** [maciej-or/hikvision_next#135]
![chrome_02VCZS8qxa](https://github.com/maciej-or/hikvision_next/assets/2862581/c8240d26-20b1-46aa-8896-8dd986b0a8cb)

doesn't work on the panel, but works in the popup, tried 264, 265, 265+

**Comment by maciej-or** [comment]
hi, on the panel there are snapshots only, refreshed every 10s, check if you granted all required permission mentioned in the readme. And check if you are able to get the snapshot directly by url:
http://{user}:{pass}@{ip}/ISAPI/Streaming/channels/101/picture
The last thing you could verify is this option:
![image](https://github.com/maciej-or/hikvision_next/assets/38075949/08abd790-3f30-47b6-80c8-f452516c1b24)

**Comment by Metam** [comment]
thanks for the detailed answer
