### ISSUE TITLE
Hikvision integration crashes latest Home Assistant 2024.2

### ISSUE THREAD

**Issue by gambit66** [maciej-or/hikvision_next#138]
I was unable to upgrade to Home Assistant 2024.2 without first deleting the Hikvision integration. This integration was causing Home Assistant to crash on startup. All the details about this crash is available on an issue logged with Home Assistant:

https://github.com/home-assistant/core/issues/109597

**Comment by msaphoto06** [comment]
Same

**Comment by vampywiz17** [comment]
same problem

**Comment by blindguynar** [comment]
same

**Comment by GroteGehaktBal** [comment]
Same here

**Comment by JohnyBeGood** [comment]
Same here on generic-x86_64

**Comment by dolenec** [comment]
Same 🫣

**Comment by Niels-Stoffer** [comment]
Same

**Comment by thefunkygibbon** [comment]
same.  its relating to to the unique id being used is a list rather than a string. 


from /config/.storage/core.config_entries
`
        "unique_id": [
          [
            "hikvision_next",
            "DS-2CD2342WD-I20160317BBWR582155793"
          ]
        ],
`

**Comment by thefunkygibbon** [comment]
also i moved my integration from my  custom_integrations folder and it still doesnt start.  I assume i must need to do something else to fully rid it from my system?  going to have to roll back to 2024.1.6 for the time being

**Comment by Steve2017** [comment]
I removed the Hikvision integration (including from HACS) and that resolved the issue. I have now been able to update to 2024.2.

Unfortunately this brings me back to the Omada issue with 2024.1.6 - that is this one:
https://github.com/home-assistant/core/issues/109339#event-11681749639
I'd been hoping that fix would be in this release but no.

**Comment by chrisuk-web** [comment]
Same here. I can delete the integration, patch HA core to 2024.2.0 but then cannot install HIKvision next as I get "unexpected error" using exactly the same field data that work if I install when core is 2024.1.6

**Comment by thefunkygibbon** [comment]
> I removed the Hikvision integration (including from HACS) and that resolved the issue. I have now been able to update to 2024.2.
> 
> Unfortunately this brings me back to the Omada issue with 2024.1.6 - that is this one: [home-assistant/core#109339 (comment)](https://github.com/home-assistant/core/issues/109339#event-11681749639) I'd been hoping that fix would be in this release but no.

probably isn't much use posting about omada in this repo :-)


Do i need to actually delete the integration completely?  from within the GUI?  i don't fancy doing that as it means i'd have to re-set up all of my automations and everything else which uses my hikvision entities :-(  not ideal.   fingers crossed that this integration is not dead and that the dev is happy to fix.

**Comment by dolenec** [comment]
Will be there any fix of HikVision integration or we must move to forward with new/other solutions?

**Comment by maciej-or** [comment]
@dolenec sure, I'm going to fix that

**Comment by ON4AHV** [comment]
Same

**Comment by Rolax68** [comment]
the same, Sorry

**Comment by dolenec** [comment]
> @dolenec sure, I'm going to fix that

And when we can expect hotfix? Will there be need to remove and reinstall integration or there should be update which will fix the problem with updating HA and it is worth of waiting.

**Comment by brave0d** [comment]
wow, guys, be patient... @maciej-or said he is on it, so he will fix it and let us know what to do to apply the fix...

there is no really point saying "me too", "same", ... etc, as the bug has been confirmed and EVERYONE who wants to use 2024.2 with this component is affected.

development is not digging rows, PATIENCE!

**Comment by dolenec** [comment]
Not being patient.. simple normal question if there is any timeline.. nothing else.. not pushing anybody anywhere..

**Comment by xoferz** [comment]
> Not being patient.. simple normal question if there is any timeline.. nothing else.. not pushing anybody anywhere..

Well, the time the author spends on estimating the timeline and answering this to you and others, is the time he is not spending on fixing the issue... 
It has not yet been a day since HA 2024-02 release. If you need a fix in less than 24 hours you can either pay someone to fix it or download the source, find the issue and fix it yourself (and share).

**Comment by arsenal3008** [comment]
I understand that no one can enter 192.168.1.67:8123?

**Comment by HuffYk** [comment]
> same. its relating to to the unique id being used is a list rather than a string.
> 
> from /config/.storage/core.config_entries
> 
> ```
>         "unique_id": [
>           [
>             "hikvision_next",
>             "DS-2CD2342WD-I20160317BBWR582155793"
>           ]
>         ],
> ```

this exactly seems to be problem... Except uninstall I tried to fix it directly in /config/.storage/core.config_entries to this:

"unique_id": "DS-2CD2342WD-I20160317BBWR582155793";

...and upgrade went ok + also hikvision integration after upgrade still works.

**Comment by maciej-or** [comment]
this line might be wrong:
https://github.com/maciej-or/hikvision_next/blob/main/custom_components/hikvision_next/config_flow.py#L68
could you confirm if:
`await self.async_set_unique_id(isapi.device_info.serial_no)`
fixes that?
(remember to restart HA after file change)

**Comment by brave0d** [comment]
@maciej-or 

> await self.async_set_unique_id(isapi.device_info.serial_no)

I am not a specialist here, but maybe better concatenate DOMAIN and serial_no?

**Comment by blindguynar** [comment]
> @maciej-or
> 
> > await self.async_set_unique_id(isapi.device_info.serial_no)
> 
> I am not a specialist here, but maybe better concatenate DOMAIN and serial_no?

i doubt its needed.  The serial# should be unique enough without requiring the domain.

**Comment by smeegoan** [comment]
To fix this issue edit file <HA>\config\custom_components\hikvision_next\config_flow.py and change line 68 from `await self.async_set_unique_id({(DOMAIN, isapi.device_info.serial_no)})` to `await self.async_set_unique_id(isapi.device_info.serial_no)`. 

I had removed this integration in order to upgrade, but with this change I manage to re add it

**Comment by smeegoan** [comment]
I did the same fix as above without checking here first and it works

**Comment by KostuaD** [comment]
> this line might be wrong: https://github.com/maciej-or/hikvision_next/blob/main/custom_components/hikvision_next/config_flow.py#L68 could you confirm if: `await self.async_set_unique_id(isapi.device_info.serial_no)` fixes that? (remember to restart HA after file change)

It worked! Thank you!

**Comment by diepeterpan** [comment]
> > same. its relating to to the unique id being used is a list rather than a string.
> > from /config/.storage/core.config_entries
> > ```
> >         "unique_id": [
> >           [
> >             "hikvision_next",
> >             "DS-2CD2342WD-I20160317BBWR582155793"
> >           ]
> >         ],
> > ```
> 
> this exactly seems to be problem... Except uninstall I tried to fix it directly in /config/.storage/core.config_entries so above example will look like this:
> 
> "unique_id": "DS-2CD2342WD-I20160317BBWR582155793",
> 
> ...and upgrade went ok + also hikvision integration after upgrade still works. However I'm not sure if this fix it correct one and it doesn't corrupt future upgrades - @maciej-or please comment if we can use this quick fix so far...

Applied this config change and the code change recommended, did a core restart, and then the update succeeded and the cameras are all still working.

**Comment by pepsonEL** [comment]
when i have installed your integration i can not update HA Core to new version 2024.2.0. It start install update but after reboot still go back to 2024.1.6
Probably it is your integration. I chanege code as you write buty nothing. Still is the same problem.

**Comment by diepeterpan** [comment]
> when i have installed your integration i can not update HA Core to new version 2024.2.0. It start install update but after reboot still go back to 2024.1.6 Probably it is your integration. I chanege code as you write buty nothing. Still is the same problem.

You must also change /config/.storage/core.config_entries aa discussed above.

**Comment by blindguynar** [comment]
> > same. its relating to to the unique id being used is a list rather than a string.
> > from /config/.storage/core.config_entries
> > ```
> >         "unique_id": [
> >           [
> >             "hikvision_next",
> >             "DS-2CD2342WD-I20160317BBWR582155793"
> >           ]
> >         ],
> > ```
> 
> this exactly seems to be problem... Except uninstall I tried to fix it directly in /config/.storage/core.config_entries so above example will look like this:
> 
> "unique_id": "DS-2CD2342WD-I20160317BBWR582155793",
> 
> ...and upgrade went ok + also hikvision integration after upgrade still works. However I'm not sure if this fix it correct one and it doesn't corrupt future upgrades - @maciej-or please comment if we can use this quick fix so far...

i wonder how many people are going to update their config file to exactly what you've put here?  :)  Not use their own serial # i mean and simply copy/paste yours ... i'd hope not, but then i watch the news and it then nothing surprises me afterwards!

**Comment by pepsonEL** [comment]
> > when i have installed your integration i can not update HA Core to new version 2024.2.0. It start install update but after reboot still go back to 2024.1.6 Probably it is your integration. I chanege code as you write buty nothing. Still is the same problem.
> 
> You must also change /config/.storage/core.config_entries as discussed above.

Ok change and now updated ok.... Thanks. 

I am waiting for update integration from @maciej-or  and maybe also update to start working motion from NVR and cameras in this integration. Now motion detect no working.

**Comment by HuffYk** [comment]
> > > same. its relating to to the unique id being used is a list rather than a string.
> > > from /config/.storage/core.config_entries
> > > ```
> > >         "unique_id": [
> > >           [
> > >             "hikvision_next",
> > >             "DS-2CD2342WD-I20160317BBWR582155793"
> > >           ]
> > >         ],
> > > ```
> > 
> > this exactly seems to be problem... Except uninstall I tried to fix it directly in /config/.storage/core.config_entries so above example will look like this:
> > 
> > "unique_id": "DS-2CD2342WD-I20160317BBWR582155793",
> > 
> > ...and upgrade went ok + also hikvision integration after upgrade still works. However I'm not sure if this fix it correct one and it doesn't corrupt future upgrades - @maciej-or please comment if we can use this quick fix so far...
> 
> i wonder how many people are going to update their config file to exactly what you've put here?  :)  Not use their own serial # i mean and simply copy/paste yours ... i'd hope not, but then i watch the news and nothing surprises me afterwards!
> 

I thought exactly about this, so rather updated my post 😁

**Comment by cp3pl** [comment]
Dzięki działa :)
await self.async_set_unique_id(isapi.device_info.serial_no)
Pozdro.

**Comment by dolenec** [comment]
After removing integration HA update went OK. But after update HACS do not find integration anymore... so can not even install it and patch the known fixes..

**Comment by thefunkygibbon** [comment]
so is /has the integration been updated or do we just need to do this fix?  will the fix survive a reload of the integration or further updates? or adding new devices

**Comment by blindguynar** [comment]
![Screenshot 2024-02-09 at 8 47 10 AM](https://github.com/maciej-or/hikvision_next/assets/48634544/17712b3c-0df9-4d94-93b1-95f7aff2b327)

2024.2.1 (just released) might make the issue mute.  Not sure as i've already applied the fix.

**Comment by msaphoto06** [comment]
I reinstalled with hacs. and HA starts.
I didn't make any changes

**Comment by JohnyBeGood** [comment]
v2024.2.1 updated just fine for me and I did not have to make any manual changes.

**Comment by thefunkygibbon** [comment]
updated HA and had added it back and it seems to be fine.   I would suggest that the integration still needs changing somewhat as i am sure that they reverted the code in HA which checks and fails for these unique id's being just strings.    it really doesnt NEED to be anything other than a string.   so if (or more likely when) they bring back the check for string, the integration likely won't work again (but hopefully shouldnt cause the whole of HA to not bootup)

**Comment by msaphoto06** [comment]
Impossib

> J'ai réinstallé avec hacs. et HA démarre. je n'ai fait aucune modification

impossible to add the camera however

**Comment by blindguynar** [comment]
> updated HA and had added it back and it seems to be fine. I would suggest that the integration still needs changing somewhat as i am sure that they reverted the code in HA which checks and fails for these unique id's being just strings. it really doesnt NEED to be anything other than a string. so if (or more likely when) they bring back the check for string, the integration likely won't work again (but hopefully shouldnt cause the whole of HA to not bootup)

Agree, but now the owner doesn't have the pressure.  I think the code fix is rather trivial based on single line that needed adjusted above.  However, I'm unsure if it will also need to go through the config flow again to correct the core.config_entries file though.  I don't know if that file is regenerated on HA update, restart, reconfiguration of an integration, and/or integration update or none or all of the above.  That's just my lack of knowledge on inner workings of HA.  Might be just new release of the hacs integration and done for all i know.

**Comment by msaphoto06** [comment]
> Code fix is ok : upgrade to 2024.2.1 is not enough Change code : https://github.com/maciej-or/hikvision_next/blob/main/custom_components/hikvision_next/config_flow.py#L68 : await self.async_set_unique_id(isapi.device_info.serial_no) Reboot Add my cameras Annke C800
> 
> Works fine ! Thanks

Top!
Work fine

**Comment by xoferz** [comment]
FWIW upgrade from 2024.1.5 to 2024.2.1 worked fine for me without any modification to hikvision_next.

**Comment by johnmmcgee** [comment]
> C800

Do you get all options?
