### ISSUE TITLE
NVR Hikvision DS-7108NI-Q1/8P error

### ISSUE THREAD

**Issue by sv2bzq** [maciej-or/hikvision_next#142]
Update 2024.2.1 but the error continues.
Work DS-7108NI-Q1/8P

This error originated from a custom integration.

Logger: custom_components.hikvision_next.config_flow
Source: custom_components/hikvision_next/config_flow.py:81
Integration: Hikvision NVR / IP Camera (documentation, issues)
First occurred: 22:22:59 (5 occurrences)
Last logged: 22:49:47

Unexpected exception [Errno -2] Name does not resolve
Unexpected exception Request URL is missing an ‘http://’ or ‘https://’ protocol.

Please any idea??

**Comment by maciej-or** [comment]
Request URL is missing an ‘http://’ or ‘https://’ protocol.
