### ISSUE TITLE
Unable to access  homeassistant

### ISSUE THREAD

**Issue by galford-fk** [maciej-or/hikvision_next#148]
Sorry, I looked for various tutorials and still can't solve it. You can only inquire here.
The model is DS-2SC3Q120MY-TE
I don’t have an NVR, so I connect the IP camera directly to the router.
Digest/basic is enabled.

There is no problem with the port settings. There are also records of HA access in the Hikvision camera logs.
The feedback of HA integration is as shown below.

![2024-03-10 201922](https://github.com/maciej-or/hikvision_next/assets/150882690/eb8755c4-b211-483f-b070-2a5c4050ed63)

Please help me.
Thanks a lot.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.12
