### ISSUE TITLE
Intrusion Detection not working

### ISSUE THREAD

**Issue by przemekp833** [maciej-or/hikvision_next#150]
Hi, the intrusion detection (as well as motion detection), shows. The intrusion detection is all set in HIK, i get all the notifications in the app etc. 

It seems the alarm server is set correctly, at least on the camera itself. This is set on each individual camera under configuration on each camera, not on the NVR, as it does not have this option (Alarm Server)

![image](https://github.com/maciej-or/hikvision_next/assets/152802870/de9b0ded-f122-4fe8-9238-f8688e4bda7b)

Nevertheless, the on the NVR device in HA it shows:

![image](https://github.com/maciej-or/hikvision_next/assets/152802870/2eba5930-4f93-4ac6-9533-2ee08cb283d9)

I'm not sure what to do to make it work to be honest. Help is appreciated. Thank you

PS. The cameras work in general, flawleslly i get the screenshots.

**Comment by przemekp833** [comment]
Thanks! Appreciated. Did it. Added the NVR again. The Diagnostic data shows everything correctly, as it is supposed. 
But the intrusion detection does not register any detection, it shows "Clear" all the time, so in this respect nothing has changed. I assume there must be something wrong elsewhere. Any support or hints appreciated

**Comment by maciej-or** [comment]
indeed, see https://github.com/maciej-or/hikvision_next/issues/149 it looks some NVRs don't support the way used by this integrations. Hikvision staff confirmed that.

**Comment by bradkeifer** [comment]
I have solved the issue I raised in #149 . Perhaps your issue has the same root causes?
