### ISSUE TITLE
Error DS-2CD1347G0-LUF

### ISSUE THREAD

**Issue by jageza1997** [maciej-or/hikvision_next#151]
Model:                    DS-2CD1347G0-LUF
Firmware Version:   V5.7.3 build 220315

![hikvsion error](https://github.com/maciej-or/hikvision_next/assets/100005351/218d960f-31e1-4292-8304-417b38952178)

**Comment by maciej-or** [comment]
duplicates https://github.com/maciej-or/hikvision_next/issues/148
