### ISSUE TITLE
Feature request for WebRTC and go2rtc compatibility

### ISSUE THREAD

**Issue by nicopret1** [maciej-or/hikvision_next#153]
Thank you for a great integration. Please consider enhancing it to be "compatible" with:

https://github.com/AlexxIT/go2rtc and https://github.com/AlexxIT/WebRTC.

**Comment by maciej-or** [comment]
Hi, I've been using [RTSPtoWeb - WebRTC](https://github.com/allenporter/stream-addons/tree/main/rtsp-to-web) so far, but I see that it is no longer being developed. I installed [go2rtc](https://github.com/AlexxIT/go2rtc) according to docs, and it works well. I can see stream card with RTC in right upper corner. The integration is compatible.

**Comment by nicopret1** [comment]
Thank you for the reply. Are you using [WebRTC Camera (integration)](https://github.com/AlexxIT/WebRTC in combination with [go2rtc](https://github.com/AlexxIT/go2rtc)? Did you add any of the cameras (added by Hikvision integration) to your go2rtc config?

If I use [WebRTC Camera](https://github.com/AlexxIT/WebRTC) together with [go2rtc](https://github.com/AlexxIT/go2rtc) I only see cameras that I've specified in the go2rtc.yaml file. However, if I use [RTSPtoWebRTC](https://www.home-assistant.io/integrations/rtsp_to_webrtc) with [go2rtc](https://github.com/AlexxIT/go2rtc) it does pick up the Hikvision integration cameras correctly.

**Comment by maciej-or** [comment]
`url` is for rtsp url, for camera use:

entity: camera.ds_7608ni_k2_8p0820200813ccrre69383646wcvu_302

**Comment by nicopret1** [comment]
Thank you. That solved my problem and the camera is now correctly displayed by [WebRTC Camera](https://github.com/AlexxIT/WebRTC)
