### ISSUE TITLE
HDD sensors not being created for DS-7616NI-M2 NVR

### ISSUE THREAD

**Issue by bradkeifer** [maciej-or/hikvision_next#156]
Diagnostics file attached.
[config_entry-hikvision_next-65457024e40113f9e83730ddb90aa365.json](https://github.com/maciej-or/hikvision_next/files/14895804/config_entry-hikvision_next-65457024e40113f9e83730ddb90aa365.json)

My NVR has a HDD, and the NVR is providing the details of the HDD to hikvision_next, but the decoding of the HDD information by `isapi.py` is failing.

During initialisation, the NVR is responding to the `GET /ISAPI/ContentMgmt/Storage` request issued by the `get_storage_devices()` function as per the below log file entry:

```
2024-04-07 14:34:55.667 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://nvr1.keifer1.duckdns.org/ISAPI/ContentMgmt/Storage [{'hdd': [{'id': '1', 'hddName': 'hdd1', 'hddPath': None, 'hddType': 'SATA', 'status': 'ok', 'capacity': '9537536', 'freeSpace': '8836096', 'property': 'RW', 'group': '1'}, {'id': '2', 'hddName': 'hdd2', 'hddPath': None, 'hddType': 'SATA', 'status': 'notexist', 'capacity': '0', 'freeSpace': '0', 'property': 'RW', 'group': '1'}]}]
```

This piece of code on line 520 in `isapi.py` is causing the method to return an empty `storage_list` and the result is that the HDD sensor(s) are not being created. I have tested removal of the code on line 520, and that does result in HDD sensor(s) being correctly created, but I assume that the code on line 520 is required by other versions of the ISAPI API or models of NVR, and hence not sure if the correct fix is the removal of this line of code or not.

```
        if "hdd" not in storage_info: return storage_list
```

**Comment by maciej-or** [comment]
Yes, this line looks redundant. As I remember there was an issue if NVR had no hdd. This case is for check.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.12
