### ISSUE TITLE
No video streams on DS-2CD2387G2-LU with v5.7.13 build 230706

### ISSUE THREAD

**Issue by rickyrickuk** [maciej-or/hikvision_next#157]
I have 6 cameras, 4 of which are working showing video streams in HA, however two aren't
The only difference I can see is that one is a DS-2CD2387G2-LU with v5.7.13 build 230706 whereas the others are v5.7.13 build 230403 (these ones work).
If I enable debugging, I get the following error on the cam that isnt displaying any streams.
![image](https://github.com/maciej-or/hikvision_next/assets/47792446/0e60d5d5-76d1-4867-8773-7af957c051c3)
I have tried main, sub, transcoded streams and the still pics also do not show.
Has anyone had this and a fix? Hik don't allow downgrading firmware so not easy to go back.
Thanks

**Comment by maciej-or** [comment]
Are you sure you use valid user and password? Please check rtsp url in another app like VLC.  Someone submitted an [issue](https://github.com/maciej-or/hikvision_next/issues/111#issuecomment-1851878123) related to special characters in the password. It waits to be fixed.

**Comment by rickyrickuk** [comment]
Thanks, didn't work via VLC and RTSP.
Found the issue, for some odd reason the Remote Live View permissions on the NVR for the ha account didn't have cams 1 and 8 ticked. 
Ticked these and all now working.
