### ISSUE TITLE
Invalid unique_id

### ISSUE THREAD

**Issue by Alexis2** [maciej-or/hikvision_next#158]
Hi,

When trying to integrate my NVR, I'm getting this error:
Config entry 'Network Video Recorder' from integration hikvision_next has an invalid unique_id '{('hikvision_next', 'DS-7732NI-M41620221227CCRRL12166039WCVU')}', please create a bug report at https://github.com/maciej-or/hikvision_next/issues

I can see the camera, the feed etc but I'm not getting any event (motion detection etc)

**Comment by maciej-or** [comment]
Please update integration to the latest version, 1.0.11 fixes that.
