### ISSUE TITLE
Persisting issue with unexpected error

### ISSUE THREAD

**Issue by d236cgc** [maciej-or/hikvision_next#169]
Hi,
I still have the issue with unexpected error. I deleted the integration until it was fixed. I have now added version 1.0.14 and i still get the unexpected error message.
Please advise, I see it is working for most people.
![IMG_0707](https://github.com/maciej-or/hikvision_next/assets/161159981/81ad59cc-5543-49b3-9804-3f00b702f9d7)
![IMG_0709](https://github.com/maciej-or/hikvision_next/assets/161159981/c5307e54-e6c2-46b1-a74f-a64825735f1a)
![image](https://github.com/maciej-or/hikvision_next/assets/161159981/9bab3675-423a-47c9-bfcb-5b59726071e5)

**Comment by maciej-or** [comment]
did v1.0.11 work for you?

**Comment by d236cgc** [comment]
No, I have tried in all possible ways. I have one of the cameras added through Generic Camera integration, could that be the issue? It is using the ip of the NVR and recognizing just camera 1.

**Comment by d236cgc** [comment]
So no ideas?
