### ISSUE TITLE
Feature Request: Modify text to be printed on camera picture

### ISSUE THREAD

**Issue by nagyrobi** [maciej-or/hikvision_next#17]
Currently can implemented like this: https://github.com/nagyrobi/home-assistant-configuration-examples/tree/main/hikvision_print_text_on_video

Would be nice to have a service call with corresponding parameters to set the text, choose the field and set postion on the picture.

**Comment by maciej-or** [comment]
That would be awesome feature. Will think about it. Thanks for sharing and inspiration.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.19
