### ISSUE TITLE
All detection sensors not working on SSL/HTTPS

### ISSUE THREAD

**Issue by FirewizzNL** [maciej-or/hikvision_next#179]
When using SSL/HTTPS on home assistant the alerts/sensors are not working.

It does not seem to accept the dns name, but IP and https also does not seem to work.

![image](https://github.com/maciej-or/hikvision_next/assets/28536443/d9a2de60-c54e-4b91-9a2f-5d937a35db5f)
![image](https://github.com/maciej-or/hikvision_next/assets/28536443/0acf1b82-3f75-4a2a-9d0b-f80518973399)
![image](https://github.com/maciej-or/hikvision_next/assets/28536443/bc35ca96-c864-41df-9d24-16ef42abcdb4)
Also the nvr does not seem to accept DNS.

NVR: DS-7604NI-K1 / 4P

**Comment by Mark7714** [comment]
Same issue here. Internally, HA sits on 8123 and my firewall forwards external requests for https://camera.myhouse.com  from 443 outside to 8123 inside and I use LetsEncrypt cert on the HA box. When the NVR on the same network tries to contact it, it fails as it asks for a cert on 8123 and there is no non-https fall back (HA doesnt allow it).

**Comment by Mark7714** [comment]
Unfortunately not I was even searching for alternate integrations last week. I'm thinking the only way I'll ever get alerts into HA from my cameras smart events through my NVR is to install Frigate onto a NUC and just avoid the issue altogether.


-------- Original message --------
From: Kevin Manders ***@***.***>
Date: 6/6/24 6:43 pm (GMT+10:00)
To: maciej-or/hikvision_next ***@***.***>
Cc: Mark Liardet ***@***.***>, Mention ***@***.***>
Subject: Re: [maciej-or/hikvision_next] All detection sensors not working on SSL/HTTPS (Issue #179)


@Mark7714<https://github.com/Mark7714> Did you find any solution or workaround yet?

**Comment by bradkeifer** [comment]
Please see the solution I implemented for #149

**Comment by FirewizzNL** [comment]
> Please see the solution I implemented for #149

This is not a solution but a workaround.

**Comment by Mark7714** [comment]
I know it’s possible but I’m not having any luck.
I have an Ecowitt weather station and there’s a brilliant and simple add-on:

EcoWitt HTTP Proxy
An HTTP proxy for Ecowitt weather stations to forward to the Ecowitt integration over HTTPS since Ecowitt does not support HTTPS..
Visit the Ecowitt HTTP Proxy page for more details

This simply opens up a http on another port and the weather station can talk to it using standard HTTP. Surely there is a HikVision NVR equivalent. I’ve spent over 6 hours trying to get the ‘NGINX Home Assistant SSL proxy’ to do this unsuccessfully.

**Comment by FirewizzNL** [comment]
@bradkeifer the workaround you provided is a good workaround. I just wanted to mention it is not a solution, it does not solve the existing problem that the API is exposed by default to https and does not accept http requests. And the NVR is only using http (in my case) and not https.

If your workaround can be implemented in the integration and be automated, it will be great. But by adding the manual proxy in NGinx is outside the integration. 
I am going to look in to it later but too busy at the moment.

**Comment by bradkeifer** [comment]
> @bradkeifer the workaround you provided is a good workaround. I just wanted to mention it is not a solution, it does not solve the existing problem that the API is exposed by default to https and does not accept http requests. And the NVR is only using http (in my case) and not https.
> 
> If your workaround can be implemented in the integration and be automated, it will be great. But by adding the manual proxy in NGinx is outside the integration. I am going to look in to it later but too busy at the moment.

Understood @FirewizzNL  I think the root cause of this problem might be nothing to do with the HIKVision integration, but perhaps more in the core of home assistant. I have been unable to get my `internal_url:` to work, and it has been defined to use http. I think that if it worked, then home assistant would be listening for both `https` and `http` and then the integration would work as expected. Have you been able to get both your `external_url:` and `internal_url:` to work?

**Comment by FirewizzNL** [comment]
@bradkeifer 
Yes I have both working, but on a valid DNS wildcard certificate. I configured outside.mydns.nl (example) through the router with portforwarding as my outside address and inside.mydns.nl as my inside address adding it as a dost to my router which forwards that traffic to home assistant. 
But the problems here for me is that:
1) My HikVision NVR does not support https on the alarm server api
2) Home assistant when https is enabled does not support (out of the box) the http usage. It only accepts https from that point on.

I know there is nginx and the nginx addon, but I prefer not to use these kinds of 'solutions'. But unfortunately I think for now there is no better workaround than that.
I have had no time to study/look in to this integration to see if something could be improved there. Busy time of the year here haha.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.1.0

**Comment by FirewizzNL** [comment]
![image](https://github.com/user-attachments/assets/f778bfdd-93bd-44cf-8eca-8313f37440ff)
![image](https://github.com/user-attachments/assets/0a92e93b-ef9b-43f5-b058-3f4c7b1b09f2)
![image](https://github.com/user-attachments/assets/9cb1f860-15f4-4783-ab5f-3b38a562eaae)

In my case the update does not solve this problem.

I have:
- NVR: DS-7604NI-K1 / 4P
- Home assistant in https mode with valid (non self signed) widcard certificate
- Unable to set host as https in NVR
- User has all rights

NVR and cameras get added but no events are seen from the camera's.
Events are sent to phone by hikvision notification center. So events work, but not on HA integration.

Do you recommend other settings for me to test, or something else?

**Comment by maciej-or** [comment]
In the new version you can also set alarm host as a domain, I though this change is related to your setup.
If you have HA on https domain you can try to change ip to domain in reconfigure dialog.
The next checkbox is related to Hikvision device cert. If NVR is on http it doesn't matter.

**Comment by FirewizzNL** [comment]
I will try but as stated in my first post, the NVR does not accept hostnames only ip's.
The problem is that the NVR wil always try to send the notifications to a non HTTPS IP endpoint.
If we cannot make HA accept data on the regular HTTP API endpoint it will never work. If HA Disables the HTTP, it rejects all notifications.

I think it can be solved if we can somehow make HA accept data over regular HTTP. 
I already tried this with NGINX but I cant get this to work with streamed data HTTP -> HTTPS. 

I am going to try with a hostname, if it works I will notify it here. Otherwise I would like the issue to remain open, since it is not resolved.

Greets, 
Kevin (Firewizz Digital Solutions)

**Comment by FirewizzNL** [comment]
Changing to hostname does not work, it also does not set the values in the nvr property, see image.
![image](https://github.com/user-attachments/assets/3c1d70bf-6460-480d-9cbc-44440841a73e)
It does not accept hostname, then it also does not accept port and it heeps http here.

**Comment by maciej-or** [comment]
did you change change alarm host in NVR UI or the integration dialog?

![image](https://github.com/user-attachments/assets/37be0d20-995d-4ae3-ace7-c42b5d65ff7a)

**Comment by FirewizzNL** [comment]
In the integration dialog, since (as you can see in my opening post image, my nvr does not accept hostnames).

**Comment by FirewizzNL** [comment]
To Recap.
![image](https://github.com/user-attachments/assets/b62d2bbc-a601-4fb9-b346-06decb79d20d)
![image](https://github.com/user-attachments/assets/90c6b08d-21cd-4932-8df1-59f7e65ed674)
![image](https://github.com/user-attachments/assets/b1729075-8916-4e1e-b260-6653ba164655)
![image](https://github.com/user-attachments/assets/2d9cc2f8-2ddd-4ebf-903b-745c5ca3083e)

**Comment by maciej-or** [comment]
Thanks for details, you are right my NVR also does not accept domain only single camera does. Unfortunately it depends on device firmware not integration.

The iIntegration sends PUT `/ISAPI/Event/notification/httpHosts` request with payload

```
<?xml version="1.0" encoding="utf-8"?>
<HttpHostNotificationList version="2.0"
  xmlns="http://www.isapi.org/ver20/XMLSchema">
  <HttpHostNotification>
    <id>1</id>
    <url>/api/hikvision</url>
    <protocolType>HTTPS</protocolType>
    <parameterFormatType>XML</parameterFormatType>
    <addressingFormatType>hostname</addressingFormatType>
    <portNo>443</portNo>
    <httpAuthenticationMethod>none</httpAuthenticationMethod>
    <Extensions xmlns="urn:selfextension:psiaext-ver10-xsd">
      <intervalBetweenEvents>0</intervalBetweenEvents>
    </Extensions>
    <hostName>ha.hostname.domain</hostName>
  </HttpHostNotification>
</HttpHostNotificationList>
```
according to the docs:

<img width="829" alt="image" src="https://github.com/user-attachments/assets/132e143f-a2cb-4515-ba1e-53795c08288f">


single camera accepts that, NVR returns 400 bad content

You can check that here:

https://github.com/maciej-or/hikvision_next/wiki/How-to-capture-ISAPI-response

**Comment by FirewizzNL** [comment]
![image](https://github.com/user-attachments/assets/27c648c0-6300-4626-9a7e-020a394baae2)

**Comment by FirewizzNL** [comment]
But correct me if i am wrong, isnt the problem just that HA does not accept the alerts over regular http?
we set a  <HttpHostNotification> which is plain http, HA works with https-only if we enable https.

The integration worked fine when used over plain http (HA).

Shouldnt there be a couple of options (of which just one is viable)
- Send alerts over https (which is not possible since hikvision NVR does not support this).
- In a way enable the HTTP endpoint in HA, i dont know if an integration is possible to do this tho.. 
- Somehow setup some http endpoint using nginx transferring the data over to HA or the HA endpoint. (which i tried but failed).

**Comment by FirewizzNL** [comment]
/Event/notification/httpHosts
Does return data tho..
`data: |
  <?xml version="1.0" encoding="UTF-8" ?>
  <HttpHostNotificationList version="1.0" xmlns="urn:psialliance-org">
  <HttpHostNotification version="1.0" xmlns="urn:psialliance-org">
  <id>1</id>
  <url>/api/hikvision</url>
  <protocolType>HTTP</protocolType>
  <parameterFormatType>XML</parameterFormatType>
  <addressingFormatType>ipaddress</addressingFormatType>
  <ipAddress>10.0.0.11</ipAddress>
  <portNo>8123</portNo>
  <httpAuthenticationMethod>none</httpAuthenticationMethod>
  <Extensions xmlns="http://www.hikvision.com/ver20/XMLSchema">
  <intervalBetweenEvents>1</intervalBetweenEvents>
  </Extensions>
  </HttpHostNotification>
  </HttpHostNotificationList>`
  Again indicating protocol type HTTP

**Comment by FirewizzNL** [comment]
Finally after some testing i noticed some other things:
- if I put the data using PUT for '/Event/notification/httpHosts' and manually set hostname, it does not persist. Even tho I do get `<statusString>OK</statusString>`.
- trying to set `<protocolType>HTTPS</protocolType>` gives ` <statusString>Invalid XML Content</statusString>`  so that does not work.
- got the ISAPI data from `https://www.use-ip.co.uk/forum/attachments/how-to-integrate-with-hikvision-lpr-function-via-isapi-pdf.2036/`;
- 
![image](https://github.com/user-attachments/assets/6ca11aa7-2dc2-458f-8d27-d17594fcf79a)

This makes me come to the conclusing the only option is to make HA accept http over its API

**Comment by maciej-or** [comment]
See ISAPI 2020 - General I shared, there is the request we are talking about: Event/notification/httpHosts, you mentioned different one. I think it depends on firmware because cameras accept https and domain.

**Comment by FirewizzNL** [comment]
Yes that was true, but my resources where from HikVision. The NVR I have does not support
` <protocolType>` to be `HTTPS`. Some other camera's and NVR's so, but not all and a HA configuration in HTTPS does not support HTTP traffic, also not over the api (incoming `/api/hikvision`).
**So this (at the moment) cannot be solved**. 
The only thing you can do (if you really need the events) is to let your HA configuration in HTTP and use NGINX to handle HTTPS (HTTPS[outside]->HTTP[HA] reverse proxy).

Or, we must somehow be able to write our own HTTP API endpoint(outside of HA) which passes data using https requests to the https endpoint of HA).

But due to time limitation and it is not that much of an urgency to me I am not going to do either.

**Comment by Mark7714** [comment]
Can someone publish the steps to make the NGinX proxy please?


-------- Original message --------
From: Kevin Manders ***@***.***>
Date: 9/12/24 7:47 pm (GMT+10:00)
To: maciej-or/hikvision_next ***@***.***>
Cc: Mark Liardet ***@***.***>, Mention ***@***.***>
Subject: Re: [maciej-or/hikvision_next] All detection sensors not working when HA in SSL/HTTPS mode (Issue #179)


Yes that was true, but my resources where from HikVision. The NVR I have does not support
<protocolType> to be HTTPS. Some other camera's and NVR's so, but not all and a HA configuration in HTTPS does not support HTTP traffic, also not over the api (incoming /api/hikvision).
So this (at the moment) cannot be solved.
The only thing you can do (if you really need the events) is to let your HA configuration in HTTP and use NGINX to handle HTTPS (HTTPS[outside]->HTTP[HA] reverse proxy).

Or, we must somehow be able to write our own HTTP API endpoint(outside of HA) which passes data using https requests to the https endpoint of HA).

But due to time limitation and it is not that much of an urgency to me I am not going to do either.

**Comment by FirewizzNL** [comment]
I think the best way is to use the addon Nginx proxy. since this is way easyer than installing nginx yourself. especially when running in a docker container.
But first you remove the section for https in HA:
```
http:
  ssl_certificate: /ssl/certificate.crt
  ssl_key: /ssl/certificate.key
  use_x_forwarded_for: true
  trusted_proxies: 
```

Then use the NGINX proxy add-on, documentation on that is not that hard I thought.
