### ISSUE TITLE
Delayed notifications of motion

### ISSUE THREAD

**Issue by tne7laa** [maciej-or/hikvision_next#18]
I have setup this with NVR DS-7608NI-K2 successfully and can see all 8 camera's with their entities.
After making an automation it gives notifications but many minutes after motion is triggered.

**Comment by maciej-or** [comment]
What automations do you mean? Please check `Logbook` of camera if  events are delayed.

**Comment by tne7laa** [comment]
Hi. 2 screen shots (these are in Dutch, sorry). 
- 1 of Autmation (Automation and Scenes)
![Scherm­afbeelding 2023-04-12 om 17 28 33 copy](https://user-images.githubusercontent.com/805474/231507962-6bd179bf-c9ea-4633-aad5-63355b88bd28.jpg)

- 2 of log of HA and on the right the time stamps of Hikvision iVMs on NVR.
![Scherm­afbeelding 2023-04-12 om 17 24 19 copy](https://user-images.githubusercontent.com/805474/231508019-67adddf6-b921-4d26-9494-d765150389fc.jpg)

Looks of it is about 2 minutes delayed.

**Comment by tne7laa** [comment]
I don't know how to test this. 
Only notification I can send from NVR is via email. These emails come after the recording itself (with pictures or not).
Or is there a way to get direct notifications from NVR, maybe via push?

**Comment by smartypantsuk** [comment]
> I don't know how to test this. Only notification I can send from NVR is via email. These emails come after the recording itself (with pictures or not). Or is there a way to get direct notifications from NVR, maybe via push?

Hikvision only supports push type notifications via the hik-connect app. You could install that and try it. You need to enable hik-connect service in nvr and install it on phone or tablet

**Comment by maciej-or** [comment]
@tne7laa I asked rather for logbook of camera device, it'd proof if delay is on NVR or automation side, sth like that 

![image](https://user-images.githubusercontent.com/38075949/231765223-369f060f-c0df-4ecb-a225-ff17c70a0852.png)

I see your NVR has no ethernet inputs for cameras so bandwidth might be crowded a bit if all 8 send something. 

@smartypantsuk  For push notifications I use HomeAssistant app on phone and PC, they come immediately, even before hik connect. But I have all cameras connected using ethernet cable. 
For managing notifications from many cameras I recommend Alarmo add on, it's a great addition to this integration.

**Comment by smartypantsuk** [comment]
> @tne7laa I asked rather for logbook of camera device, it'd proof if delay is on NVR or automation side, sth like that
> 
> ![image](https://user-images.githubusercontent.com/38075949/231765223-369f060f-c0df-4ecb-a225-ff17c70a0852.png)
> 
> I see your NVR has no ethernet inputs for cameras so bandwidth might be crowded a bit if all 8 send something.
> 
> @smartypantsuk For push notifications I use HomeAssistant app on phone and PC, they come immediately, even before hik connect. But I have all cameras connected using ethernet cable. For managing notifications from many cameras I recommend Alarmo add on, it's a great addition to this integration.

I'll look at alarmo add on.
All my cameras are connected to nvr via ethernet. 
I don't use hik connect for notifications,  only viewing cameras. 

Currently testing using HA pushover integration to get direct alerts, but I think they are virtually instant once the alerts appear in HA logbook. 
I'll try through the HA app though

**Comment by smartypantsuk** [comment]
> Hi. My NVR does work with Ethernet cable and all cameras are connected with ethernet to network.
> 
> I just setup Hik-Connect on NVR and iOS App. I did not do this because I want to leave my NVR locally and not exposed to internet (treats). After I setup Hik-connect I did get flooded with notifications from all cameras. "Notify Surveillance Center" was enabled in each camera in settings. I never did know what this does. Now I know. :-) I enabled only 1 camera and now I get instantly notifications. Also in HA! So Hik-Connect should be enabled mandatory for this I think? (For your manual?)
> 
> I don't understand why I get multiple loggings of the motion. <img alt="Scherm­afbeelding 2023-04-13 om 15 27 54" width="561" src="https://user-images.githubusercontent.com/805474/231775955-b5b228df-bc9d-4f46-95f4-f849e0dff547.png">
> 
> I have to think about leaving Hik-Connect enabled. I don't want to be hacked...

You do not need hik-connect for this integration to work.
You DO need to have "Notify Surveillance Center" enabled on all events you want to notify Home Assistant about.

**Comment by tne7laa** [comment]
> You do not need hik-connect for this integration to work. You DO need to have "Notify Surveillance Center" enabled on all events you want to notify Home Assistant about.

That's strange. I had done this before I enabled hik-connect but the notifications came after about 2 minutes (like the title says and started this post). I will try to disable hik-connect and look if notifications still come directly.

**Comment by smartypantsuk** [comment]
Let us know how you get on dowing that

**Comment by tne7laa** [comment]
I've disabled hik-connect now and get no notifications in hik-connect app. That's ok because I won't use use it (for now).
Strangely I do get instant updates from HA when Line crossing/Motion is activated. So seems to be resolved now.
Don't know why it it working now. Maybe after enable hik-connect?
So, case closed so far. Thanks for helping!

**Comment by smartypantsuk** [comment]
@maciej-or
I have noticed that if I enabled pushover notifications and HA app notifications to my phone, pushover notifications come in quicker than the HA app notifications. There isn't much in it, a few seconds perhaps.

**Comment by maciej-or** [comment]
cool, let's summarise, enabling and hik-connect reduced delays? maybe nvr restart did that? 
Notifications from HA app work for me very well and they allow to disable hik-connect if you don't need snapshot images related to event and recording preview.
Hik Alarm Server sends snapshots as well but only from stand alone camera, not from NVR, (in my case) I guess it's firmware issue and I'm waiting when it'll be improved then I could add images to this integration's notifications too.

**Comment by tne7laa** [comment]
> enabling and hik-connect reduced delays? 
It looks that way but not sure why. All I know is that before I enabled it I had a delay of about 2 minutes. But know I have disabled hik-connect on NVR again and, at this time, I don't have delays.

> maybe nvr restart did that?
No. Only thing I did was enabled hik-connect (registered and enabled my NVR in hik-connect website).
