### ISSUE TITLE
Unable to set up Integration

### ISSUE THREAD

**Issue by Prythi** [maciej-or/hikvision_next#181]
Hi,

Fresh to HA overall and getting stuck on trying to get this integration working... logs aren't giving any information to run with:

![Screenshot 2024-06-10 071147](https://github.com/maciej-or/hikvision_next/assets/172200628/b61609db-0cc8-4039-9464-a39175a12d61)

![Screenshot 2024-06-10 071622](https://github.com/maciej-or/hikvision_next/assets/172200628/ee8dcfea-d859-4f03-a2da-5bb006518ec5)

![Screenshot 2024-06-10 071646](https://github.com/maciej-or/hikvision_next/assets/172200628/aa8c1f0e-1c5a-48bd-a9c7-fa7e31bc2cc6)

HA System: Windows 11 - Hyper-V (HA OS) 
Hikvision NVR: DS-7616NI-I2/16P

I have followed the installation instructions including the alarm server details. 

Really wanting to try and get this integration running.

**Comment by maciej-or** [comment]
Hi, I wonder why there is no exception details. Cloud you please catch all logs as described here https://github.com/maciej-or/hikvision_next?tab=readme-ov-file#reporting-issues

**Comment by Prythi** [comment]
[home-assistant_2024-06-10T07-12-30.618Z.log](https://github.com/user-attachments/files/15758025/home-assistant_2024-06-10T07-12-30.618Z.log)

Hoping that didn't include important info... tried to look over it and didn't see anything vital

Can't get diagnostic logs since the integration itself doesn't start up

**Comment by Prythi** [comment]
I've played around a bit more and tried HA on virtualbox and docker but still get the exact same error and log... which makes me think there might be a firewall issue on my router or even the NVR itself??? but I can't isolate it

**Comment by maciej-or** [comment]
This integration requires the NVR and HA to be on the same network.

**Comment by maciej-or** [comment]
ofc via router, your connection seems fine, I meant
HA: 192.168.0.x
NVR: 192.168.0.y
I just wanna to make sure, did you enable integration logs: 
```
logger:
  logs:
    custom_components.hikvision_next: debug
```
then in the main log you should have entries like:
2024-06-11 14:29:55.289 DEBUG (MainThread) [custom_components.hikvision_next.isapi] --- [GET] ...
if I had that I could help more

**Comment by Prythi** [comment]
![image](https://github.com/maciej-or/hikvision_next/assets/172200628/734054d3-64a9-441f-8a10-812d3ed84b54)

Yeah i've put it into the config yaml.  

![image](https://github.com/maciej-or/hikvision_next/assets/172200628/25b749db-a78c-421f-9db4-7e16b30ee0a0)

put in the wrong account details to test

**Comment by maciej-or** [comment]
Thanks for the efforts but I have no clue what causes that exception. Is you HA up to date? Let's say version from this year?

**Comment by Prythi** [comment]
![image](https://github.com/maciej-or/hikvision_next/assets/172200628/fd3d4856-9a83-4fbf-a8a8-709a68d7cfb2)

damn...
might try an older version of HA - have played through the various settings in my NVR but nothing made a difference

**Comment by maciej-or** [comment]
no, the new one works for me, was afraid you were older

**Comment by Prythi** [comment]
Was there a record of the firmware that was used for the following NVR? Have also tried updating to the latest with no luck

7616NI-I2/16P

**Comment by Prythi** [comment]
Interesting... I can directly access the cameras, through the NVR bypass... i guess I'll just have to set up each camera individually

**Comment by maciej-or** [comment]
It is hard to find the bug if error description is empty. Maybe at least exception type would point the culprit. If you could replace line 82 in hikvision_next/config_flow.py with:
`errors["base"] = f"Unexpected {type(ex).__name__}: {ex}"`
restart HA and try setup your NVR 
then red alert in config window should display exception type

**Comment by Prythi** [comment]
Still doesn't fill...

![image](https://github.com/maciej-or/hikvision_next/assets/172200628/978569a7-6e38-4c86-ad54-1be3f7c1d49d)

And now there's no error listed in the log file
