### ISSUE TITLE
configuration failed

### ISSUE THREAD

**Issue by roma777roma** [maciej-or/hikvision_next#189]
HI,
Sorry if this is the wrong way to ask for help, but I have a problem with the integration. This is the first time I've installed it so I'm not sure I've done everything right even though there are very few fields to configure. The integration gives me a "configuration failure" on all 3 cameras (2 model DS-2CD2685FWD-IZS and 1 model DS-2CD2685FWD-IZS (B)) even if then entering into the detail of each individual camera the video flow and I see other things working

![image](https://github.com/user-attachments/assets/c4948aeb-2cf2-4a74-86a2-f84c3b01b316)

![image](https://github.com/user-attachments/assets/4fb35f74-bfd6-482d-bc34-bb02713c13fd)

![image](https://github.com/user-attachments/assets/01f5820a-1e77-4467-940c-3fd89ab5685d)

I enabled debugging in the log and among the countless lines there I saw this:

2024-07-19 11:17:18.366 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Rear Camera for hikvision_next
Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
 result = await component.async_setup_entry(hass, self)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/config/custom_components/hikvision_next/__init__.py", line 93, in async_setup_entry
 refresh_disabled_entities_in_registry(hass, isapi)
 File "/config/custom_components/hikvision_next/__init__.py", line 181, in refresh_disabled_entities_in_registry
 update_entity(event, SWITCH_ENTITY_ID_FORMAT)
 File "/config/custom_components/hikvision_next/__init__.py", line 170, in update_entity
 if entity.disabled != event.disabled:
 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'disabled'

could this be the problem?

If necessary I could attach the entire log file. Thank you very much
Andrea

**Comment by maciej-or** [comment]
Hi,
This is the best way to ask for help :)
In the last version there is small bug, it is fixed but not released yet. If you get integration from the main branch it should work for you.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.17
