### ISSUE TITLE
Annke I91DW configuration issue

### ISSUE THREAD

**Issue by elgatho** [maciej-or/hikvision_next#195]
Hello 
i have camera Annke I91DW - integration is working, it is fetching all sensors but it is shows error in configuration
```

Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.hikvision_next.notifications
Źródło: custom_components/hikvision_next/notifications.py:57
integracja: Hikvision NVR / IP Camera (dokumentacja, Problemy)
Pierwsze zdarzenie: 22:44:10 (92 zdarzenia)
Ostatnio zalogowany: 22:49:20

Cannot process incoming event ('Cannot find ISAPI instance for device %s in %s', '192.168.13.104', ['http://192.168.13.97', 'http://192.168.13.101', 'http://192.168.13.98', 'http://192.168.13.104', 'http://192.168.13.100', 'http://192.168.13.103'])
Cannot process incoming event ('Cannot find ISAPI instance for device %s in %s', '192.168.13.97', ['http://192.168.13.97', 'http://192.168.13.101', 'http://192.168.13.98', 'http://192.168.13.104', 'http://192.168.13.100', 'http://192.168.13.103'])
Cannot process incoming event ('Cannot find ISAPI instance for device %s in %s', '192.168.13.104', ['http://192.168.13.97', 'http://192.168.13.101', 'http://192.168.13.98', 'http://192.168.13.104', 'http://192.168.13.100'])
Cannot process incoming event 'ec201fc6f11924b429cd96641da732bf'
Cannot process incoming event ('Cannot find ISAPI instance for device %s in %s', '192.168.13.97', ['http://192.168.13.97', 'http://192.168.13.101', 'http://192.168.13.98', 'http://192.168.13.104', 'http://192.168.13.100'])

```
![2024-08-03 23_04_56-Ustawienia – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/eb4f198b-7bd1-4cb7-b05a-d15e6e837330)
![2024-08-03 23_05_17-Ustawienia – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/55b72f70-e01b-484b-8e1c-f963eaa6e422)

**Comment by elgatho** [comment]
Rejestrator: homeassistant.config_entries
Źródło: config_entries.py:586
Pierwsze zdarzenie: 23:20:33 (5 zdarzenia)
Ostatnio zalogowany: 23:26:04

Error setting up entry Tyl Annke for hikvision_next
Error setting up entry Annke Przod for hikvision_next
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_next/__init__.py", line 93, in async_setup_entry
    refresh_disabled_entities_in_registry(hass, isapi)
  File "/config/custom_components/hikvision_next/__init__.py", line 181, in refresh_disabled_entities_in_registry
    update_entity(event, SWITCH_ENTITY_ID_FORMAT)
  File "/config/custom_components/hikvision_next/__init__.py", line 170, in update_entity
    if entity.disabled != event.disabled:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'disabled'

**Comment by maciej-or** [comment]
how many cameras have you you added? I see 6 instance of the integration in the 1st log
second issue is fixed in https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.17
anyway please install the latest version

**Comment by maciej-or** [comment]
not enough info
