### ISSUE TITLE
Minimum HA version

### ISSUE THREAD

**Issue by mion00** [maciej-or/hikvision_next#2]
Thank you for this interesting integration!
I would like to test it with my NVR and cameras, but I am on an older release of Home Assistant (2022.8) and right now I cannot upgrade to the later ones.
What version of HA is required for this addon? Would you mind specifying it in the `hacs.json` manifest?

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.1
