### ISSUE TITLE
Every 2 minutes: Client error '403 Forbidden' for url 'http://10.20.120.210/ISAPI/System/IO/inputs/101'

### ISSUE THREAD

**Issue by xoferz** [maciej-or/hikvision_next#206]
Every 2 minutes, HA logs:
`2024-09-15 22:38:28.622 WARNING (MainThread) [custom_components.hikvision_next.isapi] Unexpected exception | Cannot fetch state for io | Client error '403 Forbidden' for url 'http://10.20.120.210/ISAPI/System/IO/inputs/101'
`
The device is DS-7616NI-K2 and user is "admin".

Disabling "NVR Alarm Input 101" entity has no effect.

**Comment by maciej-or** [comment]
please attach diagnostic data from device view

**Comment by xoferz** [comment]
this?
![Screenshot 2024-09-18 at 10 17 57](https://github.com/user-attachments/assets/5212188c-bed8-4495-9211-dfe1c7079a1c)

**Comment by maciej-or** [comment]
this: 
<img width="374" alt="image" src="https://github.com/user-attachments/assets/080dd182-d15a-4d0a-af28-b1761c351329">
Settings -> Devices -> Integration tile -> your nvr

**Comment by xoferz** [comment]
[https://drive.google.com/file/d/1-kBCeRVAHBBAKUJ2zqEHfSFuHJX50bGo/view?usp=share_link](url)

**Comment by maciej-or** [comment]
I'm leaving it for the future: 
my NVR responds on 
`ISAPI/System/IO/inputs/<ID>`
but web UI uses
`ISAPI/ContentMgmt/IOProxy/inputs/<ID>`
with similar output

You have newer firmware not available for my model so I suppose it could handle only new endpoint

**Comment by DJDunk** [comment]
I think I have the same issue? The logs show this every 2 mins. Is there anything I can do to fix it please? I also notice that the 'snapshots' are always broken on my dashboard, not sure if related.

![image](https://github.com/user-attachments/assets/8bd1bf2c-d321-456a-b503-5d09ebbc43a5)

**Comment by maciej-or** [comment]
hi, in the [v1.0.19](https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.19) new action is available which can help, please paste response from your nvr  for
`/System/IO/inputs/capabilities`

![image](https://github.com/user-attachments/assets/7a9da978-4d9d-446a-a511-65584dfd97ed)

**Comment by DJDunk** [comment]
![image](https://github.com/user-attachments/assets/d96ac808-aa4c-4286-a550-d596673d24b3)

**Comment by maciej-or** [comment]
thank you, it explains the error 403, I will change inputs detection to this request

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.1.0
