### ISSUE TITLE
get_nvr_channel_device_info  TypeError: string indices must be integers

### ISSUE THREAD

**Issue by tfi01** [maciej-or/hikvision_next#21]
Hi, I have a problem with starting the integration.
It says that:
`Logger: homeassistant.config_entries
Source: custom_components/hikvision_next/isapi.py:86
Integration: Hikvision NVR / IP Camera ([documentation](https://github.com/maciej-or/hikvision_next), [issues](https://github.com/maciej-or/hikvision_next/issues))
First occurred: 10:32:21 (5 occurrences)
Last logged: 10:42:08

Error setting up entry Network Video Recorder for hikvision_next
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
    raise ex
  File "/config/custom_components/hikvision_next/__init__.py", line 43, in async_setup_entry
    await isapi.get_nvr_capabilities()
  File "/config/custom_components/hikvision_next/isapi.py", line 110, in get_nvr_capabilities
    channel_info = self.get_nvr_channel_device_info(channel)
  File "/config/custom_components/hikvision_next/isapi.py", line 86, in get_nvr_channel_device_info
    channel_descriptor = channel["sourceInputPortDescriptor"]
TypeError: string indices must be integers`

[https://pastebin.com/UESN0cuC](url)

**Comment by maciej-or** [comment]
It's an interesting case, logs say you have camera connected to NVR over ONVIF protocol. Consider switch to HIKVISION protocol. Most of non hik devices support that. As far devices over ONVIF are not supported and I'm not sure if they could be, you can try an ONVIF integration.

**Comment by tfi01** [comment]
For some reason my camera does not support HIKVISION protocol.
Is there any chance for ignoring that camera so I can still use your integration?

**Comment by maciej-or** [comment]
fixed in [v1.0.3](https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.3)

after deeper investigation the real root of this issue was single channel returned by NVR in another format I expected, I've checked camera connected over ONVIF and it worked with notifications. In your case there is no serial or other unique id provided, (ip is to valid id). Integration skips these channels and adds warning in the log.
