### ISSUE TITLE
Thermal Camera Rules and Events Missing

### ISSUE THREAD

**Issue by Liquoriced** [maciej-or/hikvision_next#211]
I have several DS-2TD1228-2/QA cameras, which have dual regular/thermal streams.

I'm able to pull the streams both for the regular optical stream and the thermal one.
I have line crossing, instrusion and region entrance rules set up for the thermal portion of the camera under Perimeter Protection, but these are not being pulled in by Hikvision_Next into HA.

My intention is to to turn on lights in the house when specific camera rule is triggered.

**Comment by qammy** [comment]
I have a similar situation with the same requirements, slightly different camera (DS-2TD2628-3)

**Comment by maciej-or** [comment]
hi, just in time, support for that in under development and needs final tests 
https://github.com/maciej-or/hikvision_next/pull/241

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.1.0
