### ISSUE TITLE
Support Third Stream 

### ISSUE THREAD

**Issue by Sorien** [maciej-or/hikvision_next#218]
![image](https://github.com/user-attachments/assets/19343711-ea00-4732-8e7b-d74cd7a89721)

device PTZ-N2404I-DE3

**Comment by maciej-or** [comment]
isn't it available in hidden entities? 
<img width="423" alt="image" src="https://github.com/user-attachments/assets/4737f5b9-5f1e-43d6-bc34-e80986c97f61">

**Comment by maciej-or** [comment]
it should be one of them, but change codec to H.264
H.265 is not fully supported by web browsers yet
