### ISSUE TITLE
403 error on PIR sensor

### ISSUE THREAD

**Issue by marcfon** [maciej-or/hikvision_next#220]
I'm getting the following 403 error in my logs:
`2024-10-15 19:52:17.064 WARNING (MainThread) [custom_components.hikvision_next.isapi] Unexpected exception | Cannot fetch state for pir | Client error '403 Forbidden' for url 'http://192.168.0.30/ISAPI/WLAlarm/PIR'`

I've tried disabling the `switch` and `binary_sensor` entities related to pir but that didn't solve the issue.

Attached is the device diagnostics.
[config_entry-hikvision_next-01JA2VCR7QVSV9N52FK3MEFJBX.json](https://github.com/user-attachments/files/17382630/config_entry-hikvision_next-01JA2VCR7QVSV9N52FK3MEFJBX.json)

**Comment by maciej-or** [comment]
Please check permissions for the integration user
https://github.com/maciej-or/hikvision_next?tab=readme-ov-file#hikvision-device-setup-checklist
If they are OK, try admin user 
Your device is not the latest, might use different endpoint than /ISAPI/WLAlarm/PIR, can you check that somehow in browser network tab?

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.19
