### ISSUE TITLE
Entity Id naming

### ISSUE THREAD

**Issue by mperone** [maciej-or/hikvision_next#221]
Hi, I see from issue #61 that you've already thought about entity ids and came to the conclusion that users should leave them alone so you can use them in your logic without needing to have a secondary event to entity mapping. I was hoping to bring it up for reconsideration - is this something you're pretty set on? Perhaps I'm off-track but performance can't really be impacted using a tiny (on the order of hundreds) modern lookup table data structure can it?

I know I could leave the entity ids alone and deal with it, but these are used pretty substantially around yaml, automations, node-red, etc... and it's very nice to be able to name them meaningfully. (It also bothers my inner neat freak - though I'm trying to ignore it - that I have thousands of entities named the way I want and a tiny subset only from one integration that I can't rename!).

Thanks for putting together this great integration!

**Comment by maciej-or** [comment]
Hi, In the meantime logic was changed and `unique_id` is used to find entities to trigger proper event sensor. Please try to rename entity ids and report if all works correctly.

**Comment by mperone** [comment]
Thanks for the info!

I tried it out on my NVR device and it looks like the results are different for the NVR itself and the cameras it sets up as connected devices. The NVR entities all seem to be working fine after renaming the entity_ids. For the connected devices (cameras), though, it looks like to me that entities listed as 'sensors' keep working but those listed as 'controls' disconnect.

i.e. after renaming the entity_ids, binary_sensor.CAMERA_motiondetection is still working but switch.CAMERA_motiondetection is 'unknown'.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.19
