### ISSUE TITLE
Retrieve stored NVR videos

### ISSUE THREAD

**Issue by OrkhanHI** [maciej-or/hikvision_next#223]
Hi,

I am looking for ways to retrieve stored video from the NVR given the start and end date.

Is this possible?

Thanks.

**Comment by maciej-or** [comment]
Hikvision doesn't store video files, only the entire stream dump. Device exposes specific rtsp streams corresponding to events. You can choose to convert one of them to a video file and download it by additional ISAPI reuqest. See details here https://www.hikvisioneurope.com/eu/portal/portal/Technology%20Partner%20Program/03-How%20to/How%20to%20search%20and%20download%20the%20video%20file%20from%20NVR%20via%20ISAPI.pdf
