### ISSUE TITLE
I can't add camera by https (default cert)

### ISSUE THREAD

**Issue by szczukot** [maciej-or/hikvision_next#230]
Logs from HA:

This error originated from a custom integration.

Logger: custom_components.hikvision_next.config_flow
Source: custom_components/hikvision_next/config_flow.py:88
integration: Hikvision NVR / IP Camera (documentation, issues)
First occurred: 9:10:37 AM (1 occurrences)
Last logged: 9:10:37 AM

Unexpected {'SSLCertVerificationError'} [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)

**Comment by maciej-or** [comment]
So far the integration doesn't support self signed certs. Since third party hikvisionapi was removed in previous release,  it is possible to fix it. I'm going to do that.

**Comment by kingp0dd** [comment]
+1 , subscribing! :)

In the same dilemma:
https://github.com/maciej-or/hikvision_next/issues/124#issuecomment-2429643740

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.1.0
