### ISSUE TITLE
Can't enable Motion Detection

### ISSUE THREAD

**Issue by UMB8998** [maciej-or/hikvision_next#234]
Hello,

I'm trying to enable the motion detection switch and sensor, but when I do it it doesn't get activated.

Looking at the logs we have the next error:
`2024-11-03 14:02:55.821 INFO (MainThread) [custom_components.hikvision_next.isapi] --- [GET] http://10.0.0.7/ISAPI/Event/triggers/scenechangedetection-1
Client error '403 Forbidden' for url 'http://10.0.0.7/ISAPI/Event/triggers/scenechangedetection-1'`

Looking at the XML for the events on "ISAPI/Event" there is no "scenechangedetection" but there is "fielddetection" not sure if it's the same.

I'm running an iDS-7208HQHI-M1(A)/S(C) with firmware V4.75.011

**Comment by maciej-or** [comment]
Hello
fielddetection is Intrusion detection
motiondetection or vmd is Motion detection
Try to reload the integration,  if that doesn't help send the diagnostic data from device page

**Comment by UMB8998** [comment]
Hi, thank you, I tried reloading the integration, but it didn't help
This is the diagnostic of the device:
[config_entry-hikvision_next-01JBSEGN4STJE127S8QFD0FG9Q.json](https://github.com/user-attachments/files/17624387/config_entry-hikvision_next-01JBSEGN4STJE127S8QFD0FG9Q.json)

Thank you!

**Comment by maciej-or** [comment]
You must check the `Notify Supervision Center` option for each event whose sensor and switch you want to see on the HA, then reload integration or restart HA

<img width="929" alt="image" src="https://github.com/user-attachments/assets/d9008bc3-e071-4676-b645-70589611f175">

see https://github.com/maciej-or/hikvision_next?tab=readme-ov-file#hikvision-device-setup-checklist

**Comment by mrpp** [comment]
Hi, I have this issue, all my cameras are set to notify surveillance but only one seems to be detecting motion or line crossing.
