### ISSUE TITLE
Bundled events

### ISSUE THREAD

**Issue by kroese** [maciej-or/hikvision_next#24]
Hi,

If you have enabled Intrusion and Line Crossing for example, and created an automation for notifications, when both of them are triggered you get a notification for both of them.

This is expected behaviour ofcourse, but I am looking for a way to say:

- If already send a notification for any event in the last 10 seconds, do not send another one.

I think one way to solve this would be to create an extra binary state sensor, that triggers not for a specific Hikvision event, but that triggers for any event received. And that does not trigger if the previous event was less than X seconds ago.

Would it be possible to add this to your integration? Or can this already be done with some sensor scripting in HA?

**Comment by maciej-or** [comment]
I recommend you [Alarmo](https://github.com/nielsfaber/alarmo) add on. It has exactly the feature you need and many more for managing events and notifications.

![image](https://user-images.githubusercontent.com/38075949/231847247-e454c723-30ea-46e5-8443-97c594ecdd76.png)
