### ISSUE TITLE
Silent error in case alarm server can't be set

### ISSUE THREAD

**Issue by sebastian-enz** [maciej-or/hikvision_next#240]
I figured out that in case the user in the Hikvision device does not have the following permissions:

![image](https://github.com/user-attachments/assets/90dd9305-4587-49af-91d0-e5a505cec8ea)
(Sorry, in German. But the first one is the relevant one - basically saying "set parameters" or "configure device")

If the first permission isn't assigned to the user, the alarm server can't be set by the integration. This fails silently and HA won't receive any events, which can be confusing for the user.

There will be some 403s in the debug log but the user won't notice it.

I'm aware this is mentioned in the docs but still it's hard to identify as an end-user in case they forget to set the correct permissions.

**Comment by maciej-or** [comment]
right, it is visible at DEBUG level only, I'll log that as WARNING. During initialization all http errors are suppressed because many devices responses are not consistent.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.1.0
