### ISSUE TITLE
I can't add "intrusion" sensor

### ISSUE THREAD

**Issue by szczukot** [maciej-or/hikvision_next#257]
I try many times.

Every time I want to add an "intrusion" sensor, it is visible for a moment as being added and then disappears (show as disabled again).

![image](https://github.com/user-attachments/assets/7b4b8fb5-bfd5-4dca-ba48-06b94b4aede5)

**Comment by maciej-or** [comment]
`Notify Surveillance Center` is required as well as by hik-connect app and ivms-4200

<img width="665" alt="image" src="https://github.com/user-attachments/assets/56a14973-9da4-481a-8777-ff63727fd15e">
