### ISSUE TITLE
wrong sensors for motion ?

### ISSUE THREAD

**Issue by StevieWonder99a** [maciej-or/hikvision_next#261]
The log (sensors) always get information about motion.

But that ist the general motion.
The Acusense Cameras DS-2CD2386G2-ISU/SL are able to find humans or cars in the picture, and no alert will be send if there is nothing outside - animals and wind, leafs and something like this.

But Home Assistant gets always an general information. If i would use the sensor and get any automation with that - switch on a shelly with flash lights / additional alarm siren or something like this - the neightbours would geht in trouble with me because of the alerts und nobody is there ... so i cant use the sensor because it always send the general motion alert, not the special one for humans or cars.

![log](https://github.com/user-attachments/assets/434ad2d3-766f-49c2-af12-6d156bc5a0b6)

You see here all the sensors states round the day. The camera is in my backyard, and nobody is there round the day.
it looks like putting the cam on the time square in NY.
![motion](https://github.com/user-attachments/assets/63e16bb2-cbe6-429c-994f-f743e2145373)

**Comment by maciej-or** [comment]
If you have acusense camera use Intrusion Detection which is much more accurate than Motion Detection.
