### ISSUE TITLE
"Input 1" switch for each camera is disable after update to version 1.1.0

### ISSUE THREAD

**Issue by lebretr** [maciej-or/hikvision_next#263]
Hi,

After update, the "input 1" switch are disable

Previously, for my 2cd2346g2 camera, I had: 
- switch.ds_2cd2346g2_isu_sl20220518aawrj97621006_1_1_io
- binary_sensor.ds_2cd2t86g2_isu_sl20230808aawrae5480155_1_1_io

Now I have only:
- binary_sensor.ds_2cd2t86g2_isu_sl20230808aawrae5480155_1_io

Same thing for my 2 other cameras.

I tried to debug isapy.py and I think the pb is that:
- I suppose when you have a nvr, you have only one "IO input" function on channel 0
- In my case, I have 3 camera without NVR and so I have one "IO input" function for each camera, on channel 1 and port 1

I think (but I'm not sure) we should change this (line ~ 261 in get_event function):
from
```
            channel_id = 0
            io_port = 0
            is_proxy = False

            if event_id == EVENT_IO:
                io_port = int(event_trigger.get("inputIOPortID", 0))
                if not io_port:
                    io_port = int(event_trigger.get("dynInputIOPortID", 0))
                    is_proxy = io_port > 0
            else:
                channel_id = int(event_trigger.get("videoInputChannelID", 0))
                if not channel_id:
                    channel_id = int(event_trigger.get("dynVideoInputChannelID", 0))
                    is_proxy = channel_id > 0
```
to
````
            channel_id = 0
            io_port = 0
            is_proxy = False

            if event_id == EVENT_IO:
                io_port = int(event_trigger.get("inputIOPortID", 0))
                if not io_port:
                    io_port = int(event_trigger.get("dynInputIOPortID", 0))
                    is_proxy = io_port > 0
            
            if not self.device_info.is_nvr or event_id != EVENT_IO:
                channel_id = int(event_trigger.get("videoInputChannelID", 0))
                if not channel_id:
                    channel_id = int(event_trigger.get("dynVideoInputChannelID", 0))
                    is_proxy = channel_id > 0
````

**Comment by maciej-or** [comment]
Hi, I think before was wrong because IO events weren't detected properly as proxy (from devices connected by NVR) for example issue #206.
Standalone cameras have only own IO events so entities id are built according to {serial_no}_{input_port)_io
Don't you receive alarms for these events after update?

**Comment by lebretr** [comment]
I commented and I tested directly on my HA with this:

```
    # if device.device_info.is_nvr:
    for event in device.events_info:
        entities.append(EventSwitch(0, event, events_coordinator))
```

The input switch is enable again and works again: When I active the switch in HA, I see that the alarm entry is active in Hikvision web console and the input sensor is active in H.A.

**Comment by maciej-or** [comment]
You are right, should be similar as I changed for binary_sensor: 
https://github.com/maciej-or/hikvision_next/blob/main/custom_components/hikvision_next/binary_sensor.py#L32
