### ISSUE TITLE
HA via HTTPS - the recorder does not accept an HA address HTTPS.

### ISSUE THREAD

**Issue by Arek2PL** [maciej-or/hikvision_next#271]
HA via HTTPS - the recorder does not accept an HA address.

recorder: DS-7616NXI-K2, firmware V4.82.100 build 240606, hardware version B-R-K20A9_K20A9-00, web add-on version V4.0.1 build 240514, add-on version 4.0.0.3

When adding new hardware to NEXT, the HA address entered is https://192/......, the HOST address displayed by NEXT is 0.0.0.0, the host protocol is HTTP, the host port is 80. After entering the HA address http://192 /..... all values ​​returned by NEXT are valid, but protocol is HTTP, so still no communication. New firmware (V4.83.007_241031_S3000609624) didn't change anything...

After disabling the HTTPS protocol for HA (needed for external access using DuckDNS), communication between the recorder and HA using HTTP is correct.

Some cameras can communicate directly with HA via HTTPS:
DS-2CD2343G2-I firmware V5.7.14 build 231213 (in this camera you can set the HA address and protocol remotely and locally in the network/advanced/alarm server section);

Some newer cameras do not display HTTP/HTTPS information in NEXT, but work fine:
DS-2CD2347G2H-LI / V5.7.13 build 230706

Some can not...
Hilook PTZ-N4MP / V5.7.12 build 230307

Maybe this information will be useful in troubleshooting...

**Comment by maciej-or** [comment]
Hi, we have the same issue here https://github.com/maciej-or/hikvision_next/issues/179#issuecomment-2521221413
It does not dependent on the integration.
