### ISSUE TITLE
Device rename doesn't rename entities

### ISSUE THREAD

**Issue by patfelst** [maciej-or/hikvision_next#32]
Thank you and my setup
==================
Hi there - thank you so much for this integration! I got it working so easily with a DS-7608NI-I2/8P NVR and 5 cameras. The line detection and area intrusion alerts are now reliable, and its nice seeing the individual devices and entities in the integrations UI page. I've had ongoing unreliable operation with the native [Hikvision](https://www.home-assistant.io/integrations/hikvision/) integration where some alerts would not be detected (I know as I got Hikvision push notifications on my phone but not in HA), and I always had timeout errors every ten seconds in my logs.

Question
==========
My entities have very long names which I want to change, e.g.
`binary_sensor.ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_3_fielddetection`

Normally using the device rename (pencil icon), it renames all of the entities that the device has. However with this integration, the friendly name is updated ok, but the entity names do not change. I believe for this rename to work, the entity and device need to share at least some of the same string. The only way I see to rename all my entities (without doing each one manually, a total of 166 for me) I think I have to open the `config\.storage\core.entity_registry` and do a search and replace.

Would it be possible for you to update this integration so that the device name is set to the entity name prefix? e.g.
Device Name = `ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_3`
and all the entities would be named as you currently have them, like:
`binary_sensor.ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_3_motiondetection`
`binary_sensor.ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_3_tamperdetection`
`binary_sensor.ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_3_scenechangedetection`
etc

This would mean if I rename the device using the integrations UI, I would rename device from `ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_3` to `Alfresco motion` and the entities would be renamed to:
`binary_sensor.alfresco_motion_motiondetection`
`binary_sensor.alfresco_motion_tamperdetection`
`binary_sensor.alfresco_motion_scenechangedetection`

I hope that makes sense. Thanks for considering.

**Comment by maciej-or** [comment]
hi,
`binary_sensor.ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_3_fielddetection` is an `entity id`, consists of serial no, channel id and event name and corresponds to data passed in notification. You should not change `entity id`.

You can rename device using pencil icon but answer NO on this question

<img width="551" alt="image" src="https://user-images.githubusercontent.com/38075949/234355358-792457bc-b0ad-4452-96c9-7ed3efa5d9e7.png">

then only device name will be changed.

By default the integration uses real NVR's channel name as device name, 

![image](https://user-images.githubusercontent.com/38075949/234357536-05e3f3d1-c027-40f4-b150-791504680b88.png)

and entities names are prefixed by device name

![image](https://user-images.githubusercontent.com/38075949/234357226-1e741bd6-a5c6-4d31-94a9-0a8b1d07f4cf.png)

You could break something by changing entity ids, so I recommend removing all devices from integration, restart HA and add it again. I suppose you next issue is related to that.

**Comment by patfelst** [comment]
ok I removed the integration, restarted HA and added it again and have all the entities back again. I've left the names unchanged now. But in all the other HA integrations I have, you can use the device rename and select yes for rename the entities, and they still work ok, i.e. there is an underlying unique Id which the user cannot see and this does not change, so shouldn't break the connection with the underlying code.

**Comment by maciej-or** [comment]
As I wrote entity ids correspond to data passed in notifications and it allows quickly and simple update binary sensor states, because internal HA methods use entity_id for that.  I didn't want to introduce additional mapping unique_id to entity_id in place where performance and reliability is the most important.

**Comment by patfelst** [comment]
ok I think I understand. I think because many people would try and rename these entities, it would be a good idea to put a warning on the `README.md` like:

"Do not rename entities as they will no longer get updated by this integration. Entity names must conform to this format:
`Device serial no`-`channel id`-`event name` 
so that they correspond exactly to the data passed in the Hikvision device notification, for example `binary_sensor.ds_7608ni_i2_8p0820220623ccrrk17144184wcvu_1_linedetection`

Thanks again for this great add on.
