### ISSUE TITLE
Failed to setup with NVR model: DS-7616NI-E2 / 16P

### ISSUE THREAD

**Issue by RASBR** [maciej-or/hikvision_next#5]
Hi,
Sadly, didn't get it to work. below the error message from HA. any chance this will work with my NVR model?

Thanks :)

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hikvision_next/isapi.py:303
Integration: Hikvision NVR / IP Camera (documentation)
First occurred: 27 February 2023 at 19:42:11 (7 occurrences)
Last logged: 00:54:11

Error setting up entry RSBR NVR for hikvision_next
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 56, in async_setup_entry
    await isapi.set_alarm_server(
  File "/config/custom_components/hikvision_next/isapi.py", line 303, in set_alarm_server
    and host["ipAddress"] == address.hostname
KeyError: 'ipAddress'

![HIKVision NVR](https://user-images.githubusercontent.com/63133627/221695510-f39bcb31-4200-4bd3-8f72-a20b9bbba913.jpg)

**Comment by RASBR** [comment]
FYI... Tried installing integration again while UNCHECKING the alarm server creation, and it worked.

**Comment by maciej-or** [comment]
hi, thanks for testing this early version
the first issue has been submitted yesterday https://github.com/maciej-or/hikvision_next/issues/3 and is under development

403 errors can occur after NVR reboot (reload integration is needed then) or user has no permissions, please compare https://github.com/maciej-or/hikvision_next#hikvision-device-setup-checklist

**Comment by maciej-or** [comment]
please check dev branch with all fixes
https://github.com/maciej-or/hikvision_next/tree/dev
I recommend remove device from HA, copy new integration version and add device again.

**Comment by RASBR** [comment]
Sadly I am not very experienced in git and code. I think I will wait for the auto update. 

Or will a complete removal and fresh download do the same result?

**Comment by maciej-or** [comment]
you can simply download zip by clicking green button **Code** on branch page https://github.com/maciej-or/hikvision_next/tree/dev

**Comment by RASBR** [comment]
Now I get "Device is already configured" but the integration nor the entities show in HA.
I did the following:

1. Deleted contents of Folder custom_components/hikvision_next 
2. Downloaded the zipfile, placed its contents in the folder mentioned in step 1
3. Restarted HA
4. Added the integration - "Device is already configured"

Thought to share

**Comment by maciej-or** [comment]
You did not remove device as I suggested. So:
1. go to Settings / Devices & Services 
2. find existing `Hikvision NVR / IP Camera` integration tile
3. from three dots menu select Delete
now you can add NVR again using [+ Add Integration] button
I keep my fingers crossed

**Comment by RASBR** [comment]
Nothing changed.

I even tried removing the HACS integration from the 'Three dots' and download it again. same message!

**Comment by RASBR** [comment]
Hi,
Were you able to find a fix?

**Comment by maciej-or** [comment]
If removing device didn't help, the only way is modify core.device_registry file.

! PLEASE DO BACKUP before !

Edit config/.storage/core.device_registry and remove all entries associated with `hikvision_next` identifier.
Restart HA after that and try add NVR.

entries to remove will look like:

      {
        "area_id": null,
        "config_entries": [
          "ed9e2c698a48ff933f1c8d66bfde2825"
        ],
        "configuration_url": null,
        "connections": [],
        "disabled_by": null,
        "entry_type": null,
        "hw_version": null,
        "id": "51ef0f99e8cb345818aad0845a99ee07",
        "identifiers": [
          [
            "hikvision_next",
            "DS-2CD3T20D-I36ee9dc0000000000"
          ]
        ],
        "manufacturer": "Hikvision",
        "model": "DS-2CD3T20D-I3",
        "name_by_user": null,
        "name": "gate",
        "sw_version": "V5.4.23 build 161020",
        "via_device_id": "c457f09b19222a64940d4a0000000000"
      }

**Comment by RASBR** [comment]
Hi,
Firstly allow me to say big thank you!
I guess the removal was successful. I did the following:

1. Made sure I have a very recent backup (thanks for the reminder)
2. Uninstalled (removed) integration from HACS.
3. Edited 'core.device_registry' exactly as you said.
4. Rebooted HA (I have Intel NUC with HA OS)

HA restarted and seems to be working.

Did you update/fix the integration? Should I try to install again?

**Comment by maciej-or** [comment]
As far fixes are stil on dev branch, you can test it. The release will come soon.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.1

**Comment by RASBR** [comment]
Thanks for the notice. Will try soonest... hopefully tonight

**Comment by msp1974** [comment]
I wonder if this is also the same issue as #34 as it seems it is also not loading it as a NVR but individual camera.  I wonder if this is another Hikvision device_type not reporting NVR but something else?
