### ISSUE TITLE
Support for ERI-K104-P4 ?

### ISSUE THREAD

**Issue by daytonturner** [maciej-or/hikvision_next#50]
Hi there,

I'm trying to get this working with a slightly older NVR, ERI-K104-P4

I have all the required permissions and services enabled (ISAPI, etc) and it seems to fail with "credentials expired". When looking in the logs, I see:

`2023-05-27 12:35:10.592 ERROR (MainThread) [custom_components.hikvision_next.config_flow] ISAPI error Client error '401 Unauthorized' for url 'http://redacted_ip_address/ISAPI/System/status'`

Looking at a packet capture, I can see the first request to ISAPI does get a 401 Unauthorized response:

Request:
```
GET /ISAPI/System/status HTTP/1.1
Host: redacted_ip_address
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
User-Agent: python-httpx/0.24.0
Authorization: Basic YWRtaW46XXXXXXXXWNoIQ==
```

Response:
```
HTTP/1.1 401 Unauthorized
Date: Sun, 28 May 2023 09:56:24 GMT
Server: DNVRS-Webs
Cache-Control: no-cache
Content-Length: 138
Content-Type: application/xml; charset="UTF-8"
Connection: keep-alive
Keep-Alive: timeout=60, max=99
WWW-Authenticate: Digest realm="fe12f37bdXXXXXbccbbd35f1", domain="::", qop="auth", nonce="300b7e88f3d69ebfXXXXXf3e2f04218a:1685XXXXX4756", opaque="", algorithm="MD5", stale="FALSE"

<?xml version="1.0" encoding="UTF-8" ?>
<userCheck>
<statusValue>401</statusValue>
<statusString>Unauthorized</statusString>
</userCheck>
```

The NVR provides a digest auth challenge, and at this point the code doesnt seem to reply to it - perhaps this is where it's giving up, im not sure. Because If I keep watching the packet capture, it does seem to do a proper challenge/response/OK afterwards, but the hikvision_next still declares it failed with an auth error.

2 seconds after the first attempt, a new Request:
```
GET /ISAPI/System/status HTTP/1.1
Host: redacted_ip_address
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
User-Agent: python-httpx/0.24.0
```

Response:
```
HTTP/1.1 401 Unauthorized
Date: Sun, 28 May 2023 09:56:27 GMT
Server: DNVRS-Webs
Cache-Control: no-cache
Content-Length: 138
Content-Type: application/xml; charset="UTF-8"
Connection: keep-alive
Keep-Alive: timeout=60, max=99
WWW-Authenticate: Digest realm="fe12f37bXXXXXabccbbd35f1", domain="::", qop="auth", nonce="a39057b726629eXXXXXfa39c89e074df:16852XXXXX640", opaque="", algorithm="MD5", stale="FALSE"

<?xml version="1.0" encoding="UTF-8" ?>
<userCheck>
<statusValue>401</statusValue>
<statusString>Unauthorized</statusString>
</userCheck>
```

Second request this time with proper digest auth:
```
GET /ISAPI/System/status HTTP/1.1
Host: redacted_ip_address
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
User-Agent: python-httpx/0.24.0
Authorization: Digest username="admin", realm="fe12f37bXXXXXabccbbd35f1", nonce="a39057b726629eXXXXXfa39c89e074df:16852XXXXX640", uri="/ISAPI/System/status", response="b656e457f4bfb5f95b62c7a08d39XXXX", algorithm=MD5, qop=auth, nc=00000001, cnonce="8c88c8bcf620XXXX"
```

A valid 200 in response:
```
HTTP/1.1 200 OK
Date: Sun, 28 May 2023 09:56:27 GMT
Server: DNVRS-Webs
Cache-Control: no-cache
Content-Length: 526
Content-Type: application/xml; charset="UTF-8"
Connection: keep-alive
Keep-Alive: timeout=60, max=98

<?xml version="1.0" encoding="UTF-8" ?>
<DeviceStatus version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<currentDeviceTime>2023-05-28T09:56:28-08:00</currentDeviceTime>
<deviceUpTime>140189</deviceUpTime>
<CPUList>
<CPU>
<cpuDescription>2596.86</cpuDescription>
<cpuUtilization>1</cpuUtilization>
</CPU>
</CPUList>
<MemoryList>
<Memory>
<memoryDescription>DDR Memory</memoryDescription>
<memoryUsage>
226.816406</memoryUsage>
<memoryAvailable>
20.578125</memoryAvailable>
</Memory>
</MemoryList>
</DeviceStatus>
```

Then a deviceInfo Request:
```
GET /ISAPI/System/deviceInfo HTTP/1.1
Host: redacted_ip_address
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
User-Agent: python-httpx/0.24.0
Authorization: Digest username="admin", realm="fe12f37bXXXXXabccbbd35f1", nonce="a39057b726629eXXXXXfa39c89e074df:16852XXXXX640", uri="/ISAPI/System/deviceInfo", response="5a932d81fcd6a003f0412c234e9eb98d", algorithm=MD5, qop=auth, nc=00000002, cnonce="7f748a4062344fc7"
```

Response:
```
HTTP/1.1 200 OK
Date: Sun, 28 May 2023 09:56:28 GMT
Server: DNVRS-Webs
Cache-Control: no-cache
Content-Length: 630
Content-Type: application/xml; charset="UTF-8"
Connection: keep-alive
Keep-Alive: timeout=60, max=99

<?xml version="1.0" encoding="UTF-8" ?>
<DeviceInfo version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<deviceName>My Cameras</deviceName>
<deviceID>48473134-3633-3538-3139-2428fd0573d1</deviceID>
<model>ERI-K104-P4</model>
<serialNumber>ERI-K104-P40420210604CCRRG14635819WCVU</serialNumber>
<macAddress>24:28:fd:05:73:d1</macAddress>
<firmwareVersion>V3.4.100</firmwareVersion>
<firmwareReleasedDate>build 190222</firmwareReleasedDate>
<encoderVersion>V5.0</encoderVersion>
<encoderReleasedDate>build 171115</encoderReleasedDate>
<deviceType>IPC</deviceType>
<telecontrolID>255</telecontrolID>
</DeviceInfo>
```

I havent dug into the code yet, but thought I'd start by reporting here and see if you had any ideas.

Thanks!

**Comment by maciej-or** [comment]
The first request can return 401 because hikvisionapi library detects authorization type by calling basic and digest one by one
https://github.com/MissiaL/hikvision-client/blob/master/hikvisionapi/hikvisionapi.py#L118
However it shouldn't throw the exception in that case.

**Comment by daytonturner** [comment]
Yeah, I'm not sure if thats where its throwing the exception, I just see the logs claim that it cannot auth due to expired credentials, so I went looking at the packet capture to see exactly what it was doing.  It's clearly attempting the second time with the digest auth correctly, so I'm not sure - especially since it got a valid 200 response.

What else can I check or information can I gather for you?

**Comment by maciej-or** [comment]
you could enable full logs https://github.com/maciej-or/hikvision_next#reporting-issues and share here

**Comment by daytonturner** [comment]
I think this is what you're after, for debug logs from the hikvision_next component:

https://pastebin.com/zmLXuQdT

**Comment by daytonturner** [comment]
Let me know if this wasn't sufficient, or if I can do anything else to help this along?

**Comment by daytonturner** [comment]
So - great news actually, as of the v1.0.6 upgrade, authenticating and discovering cameras etc all seems to work!

There's only one remaining issue - the NVR is exposing custom ports for RTSP streams instead of 554, in this case, 33554, and opening the camera entities in HA displays a static image for a moment, then fails and marks the camera as Unavailable temporarily.  The logs show:

Error from stream worker: Error opening stream (ERRORTYPE_110, Operation timed out) rtsp://****:****@redacted.ddns.net/Streaming/channels/402

I can see there's no custom port (:33554) after the hostname, which means its still trying to use the default 554.

Is there a way to manually override this, or to have the ISAPI configuration return the 'external ports' that are configured, so the integration knows which port to use in the RTSP stream URL?

**Comment by maciej-or** [comment]
Awesome, as far default RTSP port is used only, you could manually edit this file:
custom_components/hikvision_next/isapi.py

find line:
`return f"rtsp://{self.isapi.login}:{self.isapi.password}@{self.device_info.ip_address}/Streaming/channels/{stream.id}"`

add your rtsp port:
`return f"rtsp://{self.isapi.login}:{self.isapi.password}@{self.device_info.ip_address}: 33554/Streaming/channels/{stream.id}"`

save and restart HA.

I will look for obtaining RTSP port from NVR.

**Comment by daytonturner** [comment]
This is actually what I've already done to manually override it - I turned on the debug output from the NVR/Camera API requests and searched for anything that contained the custom RTSP port number, nothing seems to be showing it so far.  Perhaps there'a another ISAPI request that could be made to retrieve it.
