### ISSUE TITLE
Shows only one channel on 16 channel DVR

### ISSUE THREAD

**Issue by peteshoard** [maciej-or/hikvision_next#51]
It may be that i am doing something wrong, but the integration only shows channel 1 in HA - how do you add the rest of the channels?

**Comment by maciej-or** [comment]
pls share full logs https://github.com/maciej-or/hikvision_next#reporting-issues then I could help more

**Comment by Shnyak** [comment]
Hello. I have a similar problem. Shows only one camera.


Logger: custom_components.hikvision_next.isapi
Source: custom_components/hikvision_next/isapi.py:483
Integration: Hikvision NVR / IP Camera (documentation, issues)
First occurred: 10:27:10 (3 occurrences)
Last logged: 10:27:11

Unexpected exception | Cannot fetch state for scenechangedetection | Unable to perform requested action. Error is Client error '403 Forbidden' for url 'http://192.168.2.10/ISAPI/Smart/SceneChangeDetection/1' For more information check: https://httpstatuses.com/403
Unexpected exception | Cannot fetch state for regionentrance | Unable to perform requested action. Error is Client error '403 Forbidden' for url 'http://192.168.2.10/ISAPI/Smart/regionEntrance/1' For more information check: https://httpstatuses.com/403
Unexpected exception | Cannot fetch state for regionexiting | Unable to perform requested action. Error is Client error '403 Forbidden' for url 'http://192.168.2.10/ISAPI/Smart/regionExiting/1' For more information check: https://httpstatuses.com/403

**Comment by Shnyak** [comment]
Thank you. This solved the problem!
