### ISSUE TITLE
MODELO HIKVISION DS-7204HGHI-SH / A(B)

### ISSUE THREAD

**Issue by JADMIM** [maciej-or/hikvision_next#56]
Buenas tardes,

no puedo configurar mi modelo que es el que esta en el enunciado me pone todo el rato que no se pudo configurar.

Como lo puedo hacer.

Gracias

**Comment by maciej-or** [comment]
I've already released big update, pls try [v1.0.6](https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.6)

**Comment by JADMIM** [comment]
buenas tardes,

no me ha funcionado con esta nueva version.

Saludos

**Comment by maciej-or** [comment]
pls open new issue in english
