### ISSUE TITLE
Update 1.06 to 1,07 even always offers after delete the package hikvision NRV/IP camera

### ISSUE THREAD

**Issue by ashkii7** [maciej-or/hikvision_next#75]
Hi,
1 - I deleted HACS from the "custom_components" file even after having restarted HA, he always offers me the update 1.06 to 1,07 for hikvision_next.
2 - I reinstalled HACS with the latest version (1.32.1) but it always asks me to update "Hikvision nvr/IP Camera" of 1.06. to 1.07.
[https://i.imgur.com/sDU2Y7e.png](https://i.imgur.com/sDU2Y7e.png)
3 - See also this issue #74 
what can I do ?
Sorry for my english, google trad is my friend ...

**Comment by maciej-or** [comment]
You can install the integration manually, unpack **hikvison_next** folder from [v1.0.7.zip](https://github.com/maciej-or/hikvision_next/archive/refs/tags/v1.0.7.zip)  into custom_components/hikvison_next and restart HA

**Comment by ashkii7** [comment]
Hi,
@maciej-or 
Sorry but I already also did that (install v1.0.7 from tour zip) and after HA reboot, it's the same, the update is still offered
[https://i.imgur.com/NyuX2M2.png](look at this screenshot)
I don't understand what's hapenned ...
