### ISSUE TITLE
Intrusion detection notification not processed

### ISSUE THREAD

**Issue by weitzelb** [maciej-or/hikvision_next#76]
Hello. I was recently wondering why there are so little intusion detections recorded. I noticed some behaviour in the logs which I had set to debug. It looks like the integration receives the notifiactions. However it is having an issue processing it. 
[debug.log](https://github.com/maciej-or/hikvision_next/files/11929894/debug.log)
_Cannot process incoming event 'NoneType' object has no attribute 'device_info'_

After that there is nothing else except the same a few more times every time the even tis triggered.

**Comment by weitzelb** [comment]
@maciej-or I have done some debugging on the code and there is a problem with the check in retrieving the ISAPI object. It is related to how a user did configure the camera. In may case it is configured with a DNS entry or an IP. The _get_isapi_instance_ function does compare the IP derived from device_ip. There is a need to validate if the configured IP is a dns name and resolve it accordingly in such case.

To elaborate, in notifications.py I added a debugging output to verify.
   def get_isapi_instance(self, device_ip) -> ISAPI:
        """Get isapi instance for device sending alert"""
        # Get list of instances
        try:
            **_LOGGER.debug("search isapi for %s", device_ip)**         
            for entry in self.hass.config_entries.async_entries(DOMAIN):
                **_LOGGER.debug("search isapi config (%s): DIS: %s - Host: %s", entry.entry_id, entry.disabled_by, entry.data.get("host"))
                _LOGGER.debug("search isapi config Host: %s =? IP %s", urlparse(entry.data.get("host")).hostname, device_ip)**

            entry = [
                entry
                for entry in self.hass.config_entries.async_entries(DOMAIN)
                if not entry.disabled_by
                and urlparse(entry.data.get("host")).hostname == device_ip
            ][0]

Currently it does compare the hostname to the cameras IP. That will not match as shown in the output below:

> 2023-07-03 17:59:24.040 DEBUG (MainThread) [custom_components.hikvision_next.notifications] search isapi config (9175c57f191f3f0753a69699bb55affe): DIS: None - Host: http://hof.mine.xyz
> 2023-07-03 17:59:24.040 DEBUG (MainThread) [custom_components.hikvision_next.notifications] search isapi config Host: hof.mine.xyz =? IP 192.168.X.X

I've changed the source, implementing a way to validate the type of teh config entry and resolve if it is a DNS name. Please check the pull request #77.

**Comment by msp1974** [comment]
@weitzelb I have submitted a PR with some changes to the way this integration notifies the binary sensor of an event to prevent it breaking if you change the entity name.  I have added your PR code into that so that we don't end up with a merge conflict as we have both amended the same notification.py code.  Hopefully @maciej-or  will be happy with both changes.

**Comment by maciej-or** [comment]
merged in v1.0.9
