### ISSUE TITLE
Event types without notifications do not show switches or binary sensor

### ISSUE THREAD

**Issue by msp1974** [maciej-or/hikvision_next#79]
I see you had to make a change to stop an error if there is no notification set on a camera (and in particular single IP cameras).  However, this now does not show the switch or binary sensor if there are no notifications set.  Is this expected behaviour?  Would it be better to do something like this so that these events do show even if no notifications are set?

Line 392 in isapi.py
```python
            notifications = support_event.get("EventTriggerNotificationList", {})

            # Fix for empty EventTriggerNotificationList in IP camera
            if not notifications:
                notifications = []
            else:
                notifications = notifications.get("EventTriggerNotification", [])
                if not isinstance(notifications, list):
                    notifications = [notifications]
```

instead of

```python
            notifications = support_event.get("EventTriggerNotificationList", {})

            # Fix for empty EventTriggerNotificationList in IP camera
            if not notifications:
                continue

            notifications = notifications.get("EventTriggerNotification", [])

            if not isinstance(notifications, list):
                notifications = [notifications]


```

**Comment by maciej-or** [comment]
Expected. I think it is a good way to hide sensors you don't use.

**Comment by msp1974** [comment]
Should this then maybe hide these if the notification to center is not set.  That way I think it makes more sense that if you don't have it setup to notify HA it will not show it.  Otherwise, I think there will be confusion as if it is set to only beep it will show but HA will not get a notification.

**Comment by maciej-or** [comment]
Now I fetch all events but disable entities without notifications https://github.com/maciej-or/hikvision_next/pull/186
