### ISSUE TITLE
unable to load with v1.0.8

### ISSUE THREAD

**Issue by SeanChengN** [maciej-or/hikvision_next#82]
Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3

`Logger: homeassistant.setup
Source: setup.py:215
First occurred: 10:07:07 (1 occurrences)
Last logged: 10:07:07

Setup failed for custom integration hikvision_next: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)`

**Comment by open1999** [comment]
Home Assistant 2023.6.3



`Logger: homeassistant.setup
Source: setup.py:215
First occurred: 04:00:47 (1 occurrences)
Last logged: 04:00:47

Setup failed for custom integration hikvision_next: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_registry.py)`
