### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Coax88** [maciej-or/hikvision_next#94]
Hi

i get Unexpected error when im try to add IP camera model DS-2CD2646G2-IZS

log in HA : Unexpected exception 'NoneType' object has no attribute 'get'

I'm using the IP address of camera and user/password.

How can i figure out what causing this.

**Comment by Kureigu07** [comment]
Same issue here with a DS-2CD2785G1-IZS.
I've created a user with the required as per the setup checklist, and have set WEB Auth to digest/basic for ISAPI access.
HA OS 10.3, HA 2023.7.1

**Comment by Coax88** [comment]
found a solution. change from H.265 to H.264
