### ISSUE TITLE
Unexpected exception 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by disforw** [maciej-or/hikvision_next#96]
I am receiving the following error when attempting to add an IP camera via ConfigFlow…

Logger: custom_components.hikvision_next.config_flow
Source: custom_components/hikvision_next/config_flow.py:81 
Integration: Hikvision NVR / IP Camera (documentation, issues) 
First occurred: 9:39:15 PM (2 occurrences) 
Last logged: 9:39:17 PM

Unexpected exception 'NoneType' object has no attribute 'get'

**Comment by Loic691** [comment]
Same for me. I can't load the integration for my hikdevice
