### ISSUE TITLE
Scene Change Detection entity is now not present

### ISSUE THREAD

**Issue by Loic691** [maciej-or/hikvision_next#98]
Hi
Since, one or 2 two update, I have to add the check manually for the predense or not in a HDD in the camera.
But after applied this modification waiting the PR, the entity Scene Change Detection is not present.
I think there is no link between these 2 things.

It was OK before.
Do you have any idea for this ?
My HIK camera version and firmware :
DS-2CD2146G2
firmware 5.7.13
The link method in the camera config is OK. and we can enable/disable the scene detection from the device itself but just the entity is now  not visible in hikvision_next...

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.16

**Comment by Loic691** [comment]
Hi
The issue iq already présent since more one yearq.
Th e scène detection evebts and switch works with an other domotics solution.
How can i help to solde it ?

**Comment by maciej-or** [comment]
pls attach diagnostic data of your nvr available on device page, then I could simulate your setup in test environment.

**Comment by Loic691** [comment]
I have no nvr.
This is the scene detection of hikvision camera
Can we have diag data as on nvr ?

**Comment by maciej-or** [comment]
Diagnostic data is available for any device. Just go to the device page and download: 
![image](https://github.com/user-attachments/assets/91572580-351a-4917-8885-3fa1820a0eb6)

**Comment by Loic691** [comment]
Hi
Thanks. I become to search on cam itself... ;-)
Here's 2 diag file
"isSupportSceneChangeDetection" is been supported !

[config_entry-hikvision_next-01J2XCR3592AWRQ9A2YPEZKG4D.json](https://github.com/user-attachments/files/16405296/config_entry-hikvision_next-01J2XCR3592AWRQ9A2YPEZKG4D.json)

[config_entry-unifi-b0c95d01ad53d62e9c000d9f9510d1e3.json](https://github.com/user-attachments/files/16405297/config_entry-unifi-b0c95d01ad53d62e9c000d9f9510d1e3.json)

**Comment by maciej-or** [comment]
I'm afraid you did not upgrade the integration to v1.0.16, you are still on v1.0.15.  Remember to restart HA after upgrade.

**Comment by Loic691** [comment]
Yes because i had the bug on starting on the last stable which is correctement but not déployer on hacs...

**Comment by maciej-or** [comment]
right, the bug is fixed but not released yet, pls pull main branch of the integration

**Comment by Loic691** [comment]
> right, the bug is fixed but not released yet, pls pull main branch of the integration

Oh done
And scene detection appears ;-)
Thanks

PS : Is there plan into integration to get more events when available. For example  type of intrusion : vehicule, person,.. and zone ?
In the past I writed a plugin for another platform (jeedom) and I get these type of events.

Regards

**Comment by maciej-or** [comment]
Intrusion detection and region entrance, exiting are supported. As far as I know there is no intrusion type included in the alert (person or vehicle). 
Regarding faces and car plates recognition, my equipment does not support them so I have not enough data to implement that.
If I had XML files with these alerts sent by Hikvision device, like https://github.com/maciej-or/hikvision_next/blob/main/tests/fixtures/ISAPI/EventNotificationAlert/ipc_1_fielddetection.xml 
I could try adding this in a test environment. I am able to simulate any device with its diagnostic data.
If you would like to contribute the integration I can help and do code reviews.

**Comment by Loic691** [comment]
Yes we have these information in XML. I used it with my old  module in jeedom.
We can have zone and type of object.

I can try to get time to send you XML files for each events. If i am right we have thsvobject for each event.

I have to find in my old notes the debug mode of the URL of the camera to have this.

My camera is  acusense one.

**Comment by maciej-or** [comment]
Any notification XML should begin from <EventNotificationAlert> node. 
For adding sensors and switches I need to know if device supports an event and if it is enabled. According to the documentation there is several endpoints for that
events supported: ISAPI/System/capabilities
events enabled: ISAPI/Event/triggers/
diagnostic data contains 2 above 
more over some events have separate URL with enabled state:
Human face detection：/ISAPI/Event/triggers/faceDetect/
Human face identification：/ISAPI/Event/triggers/FaceDiscern/
License plate identification：/ISAPI/Event/triggers/platLicenseRecog/

**Comment by Loic691** [comment]
Here's the JSON I have for fielddetection
```
{
    "EventNotificationAlert": {
        "$": {
            "version": "2.0",
            "xmlns": "http://www.hikvision.com/ver20/XMLSchema"
        },
        "ipAddress": "192.168.2.5",
        "ipv6Address": "::ffff:192.168.2.5",
        "portNo": "80",
        "protocol": "HTTP",
        "macAddress": "ac:b9:2f:49:44:75",
        "channelID": "1",
        "dateTime": "2022-01-31T13:53:05+01:00",
        "activePostCount": "1",
        "eventType": "fielddetection",
        "eventState": "active",
        "eventDescription": "fielddetection alarm",
        "DetectionRegionList": {
            "DetectionRegionEntry": {
                "regionID": "3",
                "sensitivityLevel": "50",
                "RegionCoordinatesList": {
                    "RegionCoordinates": [{
                            "positionX": "572",
                            "positionY": "100"
                        }, {
                            "positionX": "572",
                            "positionY": "995"
                        }, {
                            "positionX": "999",
                            "positionY": "998"
                        }, {
                            "positionX": "992",
                            "positionY": "210"
                        }
                    ]
                },
                "detectionTarget": "human",
                "TargetRect": {
                    "X": "0.6",
                    "Y": "0.215278",
                    "width": "0.135937",
                    "height": "0.505556"
                }
            }
        },
        "channelName": "COUR NORD",
        "detectionPictureTransType": "binary",
        "detectionPicturesNumber": "1",
        "isDataRetransmission": "false"
    }
}

```
